### ISSUE TITLE
Is there a way to add a quick-start entry to Launchpad?

### ISSUE THREAD

**Issue by fkpwolf** [jeffreywildman/homebrew-virt-manager#100]
I used this tool at my working time. Really useful. But I have to start it from Terminal. It would be better to add a quick-start icon to Launchpad or  Dock?

**Comment by jb-alvarado** [comment]
You can write a apple script:

```
do shell script "/usr/local/bin/virt-manager --no-fork -c 'qemu+ssh://user@example.org/system?socket=/var/run/libvirt/libvirt-sock' > /dev/null 2>&1 &"
```

and save it as a App.

You can also specify an icon, if you want :).

**Comment by fkpwolf** [comment]
Thanks. I fetch image file from https://github.com/virt-manager/virt-manager/tree/master/data/icons and make a icon files by [this way](https://stackoverflow.com/questions/12306223/how-to-manually-create-icns-files-using-iconutil).
[apple.icns.zip](https://github.com/jeffreywildman/homebrew-virt-manager/files/2165000/apple.icns.zip)
