### ISSUE TITLE
Drop-down content is not loaded

### ISSUE THREAD

**Issue by 0xD4** [jeffreywildman/homebrew-virt-manager#105]
When creating a new VM, the content for selecting the OS in the drop-down menu is not loaded. This results in an error when you click on "continue" (see attachments).

I am using Virt-Manager 1.5.1, Brew 1.7.1 with macOS 10.13.6 (17G65).

![virt-manager](https://user-images.githubusercontent.com/12544860/43758462-74db8840-9a1c-11e8-87fe-8dd20bf49cb0.png)
![virt-manager2](https://user-images.githubusercontent.com/12544860/43758464-77b52c2e-9a1c-11e8-956d-eab0d9d616be.png)

**Comment by jeffreywildman** [comment]
Closing, think this is a duplicate of #64
