### ISSUE TITLE
Unable to connect to different port

### ISSUE THREAD

**Issue by dgomez** [jeffreywildman/homebrew-virt-manager#106]
It's possible to connect to a remote host via qemu+ssh using a different port for SSH than default 22?

**Comment by RocKordier** [comment]
Hey,
of course its possible! Simply define a host config in `~ /.ssh /config` and use the shortcut when connecting through virt-manager

```virt-manager -c "qemu+ssh://server/system?socket=/var/run/libvirt/libvirt-sock"```
```
Host server
	Hostname 8.8.8.8
	User remoteuser
	Port 2323
```
Eric

**Comment by dgomez** [comment]
Great!
Thanks!
