### ISSUE TITLE
Connecting to local

### ISSUE THREAD

**Issue by marirs** [jeffreywildman/homebrew-virt-manager#108]
Here is how I connect to the local system and administrate:

1) make sure libvirtd is installed. Once installed you can start the service like this:
`brew services start libvirt`
2) If started you should find the pid and the sock file here:
`~/.cache/libvirt/`
3) Now run the command in the terminal (replace \<user\> with your username)
`sudo virt-manager -c 'qemu:///session?socket=/Users/<user>/.cache/libvirt/libvirt-sock'`

**Comment by roolebo** [comment]
@marirs The last line can be reduced to `virt-manager -c 'qemu:///session'`

**Comment by marirs** [comment]
@roolebo Thanks, that works too :)
