### ISSUE TITLE
Uninstall command? 

### ISSUE THREAD

**Issue by punkrokk** [jeffreywildman/homebrew-virt-manager#110]
When uninstalling - what would be the proper command?

**Comment by roolebo** [comment]
This is [documented](https://docs.brew.sh/FAQ#how-do-i-uninstall-a-formula) in homebrew FAQ.

**Comment by punkrokk** [comment]
yes, I see that. I thought there might be a cleaner way. ...

**Comment by jeffreywildman** [comment]
Answered by @roolebo, closing.

**Comment by punkrokk** [comment]
So - I don't think this has really been addressed. 

I was unable to "cleanly" remove virt-manager.

1. provide a methodology to do a uninstall that is non-destructive 
2. warn on the readme page that this installs **MANY** packages, and the uninstalling it **MAY** break your brew environment (or use `brew uninstall --force virt-manager virt-viewer`)or force you to reinstall brew and your packages from scratch.

**Comment by roolebo** [comment]
@punkrokk Perhaps I'm missing something. So you wanted to remove virt-manager and virt-viewer, and you did run:
```
brew uninstall --force virt-manager virti-viewer
```
What went wrong?
