### ISSUE TITLE
Any chance of a .app for to be stored in the `Applications` folder for easy association?

### ISSUE THREAD

**Issue by lynndixon** [jeffreywildman/homebrew-virt-manager#111]
Maybe its me, but I am trying to use remote-viewer, and I have to download my .vv file, save it, and then open it from the command line using `remote-viewer console.vv` everytime.  

I can't find a way to associate the console.vv files to an actual application because remote-viewer lives in /usr/local/bin/ and OSX only wants to associate with apps in the Applications folder, where a .app is needed?

**Comment by fridtjof** [comment]
You might find a solution by using Automator.app to create a very simple workflow that just launches remote-viewer, and exporting that as an app bundle. You might be able to assign the file type to that app, then.

**Comment by jeffreywildman** [comment]
Using `remote-viewer` 8.0, I don't see any options to save a `*.vv` file. However, on startup, I am prompted with the option to type a new URI or select from a list of previously used URIs.

Happy to consider alternatives, but sounds like this customization is better left out of the formula. Labeling wontfix for now.
