### ISSUE TITLE
ImportError: Typelib file for namespace 'GLib', version '2.0' not found

### ISSUE THREAD

**Issue by choclo** [jeffreywildman/homebrew-virt-manager#123]
Hi guys,

First of all thanks for such a great app. I'm having some issues running virt-manager. Every time I run it I get the following:

```
tomas@MacBook-Pro:~$ virt-manager
Traceback (most recent call last):
  File "/usr/local/opt/pygobject3/lib/python3.7/site-packages/gi/importer.py", line 138, in load_module
    introspection_module = get_introspection_module(namespace)
  File "/usr/local/opt/pygobject3/lib/python3.7/site-packages/gi/module.py", line 265, in get_introspection_module
    module = IntrospectionModule(namespace, version)
  File "/usr/local/opt/pygobject3/lib/python3.7/site-packages/gi/module.py", line 117, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Typelib file for namespace 'GLib', version '2.0' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.1.0/libexec/share/virt-manager/virt-manager", line 18, in <module>
    from gi.repository import LibvirtGLib
  File "/usr/local/opt/pygobject3/lib/python3.7/site-packages/gi/importer.py", line 140, in load_module
    raise ImportError(e)
ImportError: Typelib file for namespace 'GLib', version '2.0' not found

```

I tried reinstalling gstreamer but to no avail. What else can be done?

Thanks!

**Comment by jeffreywildman** [comment]
Formula `pygobject3` contains a test that looks like it would cover this error. Would you run the following to see if it passes:

```
brew test pygobject3
```

**Comment by choclo** [comment]
Great, that did it! Thanks!!! :-)

**Comment by Valentyna** [comment]
@choclo so what exactly did you do? I'm having same error
running `brew test pygobject3` doesn't seam to suggest the solution

**Comment by choclo** [comment]
> @choclo so what exactly did you do? I'm having same error
> running `brew test pygobject3` doesn't seam to suggest the solution
> `brew reinstall pygobject3` didn't help either

I just did what @jeffreywildman suggested here https://github.com/jeffreywildman/homebrew-virt-manager/issues/123#issuecomment-526936479

**Comment by Valentyna** [comment]
got it, thanks
Anyway,  I managed to fix mine only by reinstalling homebrew

**Comment by b1scoito** [comment]
In this case, `brew test pygobject3` only runs a test that imports the `GLib` library. To actually fix this issue you need to run 
```
$ brew link glib
```
as seen in the output of `brew doctor`.
