### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by Clevelus** [jeffreywildman/homebrew-virt-manager#125]
brew install virt-manager virt-viewer
...
`######################################################################## 100.0%
==> Pouring vte3-0.56.0.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/vte3/0.56.0: 150 files, 4.3MB
==> Installing jeffreywildman/virt-manager/virt-manager
==> Downloading https://virt-manager.org/download/sources/virt-manager/virt-manager-2.1.0.tar.gz
==> Downloading from https://releases.pagure.org/virt-manager/virt-manager-2.1.0.tar.gz
######################################################################## 100.0%
==> Patching
patching file virt-manager
==> Downloading https://files.pythonhosted.org/packages/37/db/89d6b043b22052109da35416abc3c397655e4bd3cff031446ba02b9654fa/virtualenv-16.4.3.tar.gz
######################################################################## 100.0%
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/virt-manager--homebrew-virtualenv-20190322-37447-1gvw6el/target --install-scripts=/private/tmp/virt-manager--homebrew-virtualenv-20190322-37447-1gvw6el/target
Last 15 lines from /Users/clevelus/Library/Logs/Homebrew/virt-manager/01.python3:
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/private/tmp/virt-manager--homebrew-virtualenv-20190322-37447-1gvw6el/target
--install-scripts=/private/tmp/virt-manager--homebrew-virtualenv-20190322-37447-1gvw6el/target/bin
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
osx virt-manager console screen is black https://github.com/jeffreywildman/homebrew-virt-manager/issues/113
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62`

**Comment by firemen20** [comment]
can't install virt-manage :
Last 15 lines from /Users/frank/Library/Logs/Homebrew/virt-manager/01.python3:
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/private/tmp/virt-manager--homebrew-virtualenv-20190407-46497-1jfklvg/target
--install-scripts=/private/tmp/virt-manager--homebrew-virtualenv-20190407-46497-1jfklvg/target/bin
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
osx virt-manager console screen is black https://github.com/jeffreywildman/homebrew-virt-manager/issues/113
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62

**Comment by jeffreywildman** [comment]
I think homebrew migrated from python2 to python3 around this time. Confirming that `python3` is installed correctly via homebrew may help.

**Comment by asergeant01** [comment]
I have the same error and confirmed python3 is installed via homebrew.

**Comment by asergeant01** [comment]
I got it installed by running `brew postinstall python3`

**Comment by jeffreywildman** [comment]
@asergeant01 thanks for the update, glad it's running.
