### ISSUE TITLE
Install error "mkdir"and how to fix

### ISSUE THREAD

**Issue by firemen20** [jeffreywildman/homebrew-virt-manager#127]

**Comment by firemen20** [comment]
2. brew install virt-manager virt-viewer
###报错 Error: An unexpected error occurred during the `brew link` step 解决办法
### Error: An unexpected error occurred during the `brew link` step
### The formula built, but is not symlinked into /usr/local
### Permission denied @ dir_s_mkdir - /usr/local/Frameworks
### Error: Permission denied @ dir_s_mkdir - /usr/local/Frameworks

fix
命令行：

`sudo mkdir /usr/local/Frameworks`

`sudo chown -R $(whoami) /usr/local/Frameworks`

RUN again 
命令行
`brew install virt-manager virt-viewer
`

**Comment by jeffreywildman** [comment]
This is a general homebrew file permissions issue, closing.
