### ISSUE TITLE
Request: document where settings are stored

### ISSUE THREAD

**Issue by seanhoughton** [jeffreywildman/homebrew-virt-manager#130]
I've been searching every corner of the internet trying to figure out where the list of stored connections is loaded from. I tried looking through the source code but it seems to want to store configs at

```py
self.conf_dir = "/org/virt-manager/%s/" % self.appname
```

which is not valid on MacOS.

**Comment by jeffreywildman** [comment]
Duplicate of #61

**Comment by klepek** [comment]
@seanhoughton , in #61 there is answer to your question
