### ISSUE TITLE
Install error with virt-manager

### ISSUE THREAD

**Issue by mrkita** [jeffreywildman/homebrew-virt-manager#131]
I tried today to install this on my host installation of Mojave 10.14.5.

At first I ran into the problem found in issue #125 , but after running `brew postinstall python3` I get a new error everytime to run `brew install virt-manager`:

==> /usr/local/Cellar/virt-manager/2.2.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/virt-manager--libvirt-python-20190710-2453-1my540v/libvirt-python-5.4.0
Last 15 lines from /Users/kimo/Library/Logs/Homebrew/virt-manager/03.pip:
Removed build tracker '/private/tmp/pip-req-tracker-061k8jwc'
ERROR: Command "/usr/local/Cellar/virt-manager/2.2.0/libexec/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/pip-req-build-nvcxlhh3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-f9_xan4w/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/2.2.0/libexec/bin/../include/site/python3.7/libvirt-python" failed with error code 1 in /private/tmp/pip-req-build-nvcxlhh3/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.2.0/libexec/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/virt-manager/2.2.0/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 414, in run
    use_user_site=options.use_user_site,
  File "/usr/local/Cellar/virt-manager/2.2.0/libexec/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/usr/local/Cellar/virt-manager/2.2.0/libexec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 951, in install
    spinner=spinner,
  File "/usr/local/Cellar/virt-manager/2.2.0/libexec/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/usr/local/Cellar/virt-manager/2.2.0/libexec/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/pip-req-build-nvcxlhh3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-f9_xan4w/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/2.2.0/libexec/bin/../include/site/python3.7/libvirt-python" failed with error code 1 in /private/tmp/pip-req-build-nvcxlhh3/

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
osx virt-manager console screen is black https://github.com/jeffreywildman/homebrew-virt-manager/issues/113
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62

I have tried reinstalling python3, the pip setup tools module, and brew doctor/cleanup.

I am on python 3.7 through brew.

Any ideas?

**Comment by stewartadam** [comment]
Same issue here, here is the contents of `~/Library/Logs/Homebrew/virt-manager/03.pip`:

```
2019-07-10 16:46:15 -0700

/usr/local/Cellar/virt-manager/2.2.0/libexec/bin/pip
install
-v
--no-deps
--no-binary
:all:
--ignore-installed
/private/tmp/virt-manager--libvirt-python-20190710-24569-fzntmr/libvirt-python-5.4.0

Created temporary directory: /private/tmp/pip-ephem-wheel-cache-cbj473gq
Created temporary directory: /private/tmp/pip-req-tracker-ew78urnt
Created requirements tracker '/private/tmp/pip-req-tracker-ew78urnt'
Created temporary directory: /private/tmp/pip-install-hvcrjtsp
Processing /private/tmp/virt-manager--libvirt-python-20190710-24569-fzntmr/libvirt-python-5.4.0
  Created temporary directory: /private/tmp/pip-req-build-vl576z0e
  Added file:///private/tmp/virt-manager--libvirt-python-20190710-24569-fzntmr/libvirt-python-5.4.0 to build tracker '/private/tmp/pip-req-tracker-ew78urnt'
    Running setup.py (path:/private/tmp/pip-req-build-vl576z0e/setup.py) egg_info for package from file:///private/tmp/virt-manager--libvirt-python-20190710-24569-fzntmr/libvirt-python-5.4.0
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/libvirt_python.egg-info
    writing pip-egg-info/libvirt_python.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/libvirt_python.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/libvirt_python.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/libvirt_python.egg-info/SOURCES.txt'
    file build/libvirt.py (for module libvirt) not found
    file build/libvirt_qemu.py (for module libvirt_qemu) not found
    file build/libvirt_lxc.py (for module libvirt_lxc) not found
    file build/libvirtaio.py (for module libvirtaio) not found
    reading manifest file 'pip-egg-info/libvirt_python.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/libvirt_python.egg-info/SOURCES.txt'
  Source in /private/tmp/pip-req-build-vl576z0e has version 5.4.0, which satisfies requirement libvirt-python==5.4.0 from file:///private/tmp/virt-manager--libvirt-python-20190710-24569-fzntmr/libvirt-python-5.4.0
  Removed libvirt-python==5.4.0 from file:///private/tmp/virt-manager--libvirt-python-20190710-24569-fzntmr/libvirt-python-5.4.0 from build tracker '/private/tmp/pip-req-tracker-ew78urnt'
Skipping bdist_wheel for libvirt-python, due to binaries being disabled for it.
Installing collected packages: libvirt-python
  Created temporary directory: /private/tmp/pip-record-o_h838up
  Running setup.py install for libvirt-python: started
    Running command /usr/local/Cellar/virt-manager/2.2.0/libexec/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/pip-req-build-vl576z0e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-o_h838up/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/2.2.0/libexec/bin/../include/site/python3.7/libvirt-python
    running install
    running build
    /usr/local/opt/pkg-config/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
    /usr/local/Cellar/virt-manager/2.2.0/libexec/bin/python3.7 generator.py libvirt /usr/local/Cellar/libvirt/5.5.0/share/libvirt/api/libvirt-api.xml
    Found 461 functions in /usr/local/Cellar/libvirt/5.5.0/share/libvirt/api/libvirt-api.xml
    Found 0 functions in libvirt-override-api.xml
    Generated 367 wrapper functions
    Missing type converters:
    virNetworkPortPtr **:1
    virNetworkPortPtr:12
    ERROR: failed virNetworkListAllPorts
    ERROR: failed virNetworkPortCreateXML
    ERROR: failed virNetworkPortDelete
    ERROR: failed virNetworkPortFree
    ERROR: failed virNetworkPortGetNetwork
    ERROR: failed virNetworkPortGetParameters
    ERROR: failed virNetworkPortGetUUID
    ERROR: failed virNetworkPortGetUUIDString
    ERROR: failed virNetworkPortGetXMLDesc
    ERROR: failed virNetworkPortLookupByUUID
    ERROR: failed virNetworkPortLookupByUUIDString
    ERROR: failed virNetworkPortRef
    ERROR: failed virNetworkPortSetParameters
    error: command '/usr/local/Cellar/virt-manager/2.2.0/libexec/bin/python3.7' failed with exit status 1
  Running setup.py install for libvirt-python: finished with status 'error'
Cleaning up...
  Removing source in /private/tmp/pip-req-build-vl576z0e
Removed build tracker '/private/tmp/pip-req-tracker-ew78urnt'
ERROR: Command "/usr/local/Cellar/virt-manager/2.2.0/libexec/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/pip-req-build-vl576z0e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-o_h838up/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/2.2.0/libexec/bin/../include/site/python3.7/libvirt-python" failed with error code 1 in /private/tmp/pip-req-build-vl576z0e/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.2.0/libexec/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/virt-manager/2.2.0/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 414, in run
    use_user_site=options.use_user_site,
  File "/usr/local/Cellar/virt-manager/2.2.0/libexec/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/usr/local/Cellar/virt-manager/2.2.0/libexec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 951, in install
    spinner=spinner,
  File "/usr/local/Cellar/virt-manager/2.2.0/libexec/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/usr/local/Cellar/virt-manager/2.2.0/libexec/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/pip-req-build-vl576z0e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-o_h838up/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/2.2.0/libexec/bin/../include/site/python3.7/libvirt-python" failed with error code 1 in /private/tmp/pip-req-build-vl576z0e/

HOMEBREW_VERSION: 2.1.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2b83463091513826127c14acae81a7c354dfce69
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 32dbecace506560608b62ce84f898309bfcbb977
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CACHE: /Users/myuser/Library/Caches/Homebrew
HOMEBREW_LOGS: /Users/myuser/Library/Logs/Homebrew
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.22.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_191
macOS: 10.14.5-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: N/A
CLT headers: 10.2.1.0.1.1554506761

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j12
CMAKE_PREFIX_PATH: /usr/local/opt/gettext:/usr/local/opt/libffi:/usr/local/opt/openssl:/usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local/opt/icu4c:/usr/local/opt/libxml2:/usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/python/Frameworks:/usr/local/opt/python@2/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/fontconfig/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/python/lib/pkgconfig:/usr/local/opt/glib/lib/pkgconfig:/usr/local/opt/lzo/lib/pkgconfig:/usr/local/opt/pixman/lib/pkgconfig:/usr/local/opt/cairo/lib/pkgconfig:/usr/local/opt/jpeg/lib/pkgconfig:/usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/gdk-pixbuf/lib/pkgconfig:/usr/local/opt/libcroco/lib/pkgconfig:/usr/local/opt/fribidi/lib/pkgconfig:/usr/local/opt/graphite2/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/harfbuzz/lib/pkgconfig:/usr/local/opt/pango/lib/pkgconfig:/usr/local/opt/librsvg/lib/pkgconfig:/usr/local/opt/atk/lib/pkgconfig:/usr/local/opt/libepoxy/lib/pkgconfig:/usr/local/opt/gtk+3/lib/pkgconfig:/usr/local/opt/libtasn1/lib/pkgconfig:/usr/local/opt/nettle/lib/pkgconfig:/usr/local/opt/p11-kit/lib/pkgconfig:/usr/local/opt/libevent/lib/pkgconfig:/usr/local/opt/unbound/lib/pkgconfig:/usr/local/opt/gnutls/lib/pkgconfig:/usr/local/opt/libgpg-error/lib/pkgconfig:/usr/local/opt/gtk-vnc/lib/pkgconfig:/usr/local/opt/gtksourceview4/lib/pkgconfig:/usr/local/opt/check/lib/pkgconfig:/usr/local/opt/libidn2/lib/pkgconfig:/usr/local/opt/libpsl/lib/pkgconfig:/usr/local/opt/webp/lib/pkgconfig:/usr/local/opt/gd/lib/pkgconfig:/usr/local/opt/jasper/lib/pkgconfig:/usr/local/opt/netpbm/lib/pkgconfig:/usr/local/opt/gts/lib/pkgconfig:/usr/local/opt/graphviz/lib/pkgconfig:/usr/local/opt/vala/lib/pkgconfig:/usr/local/opt/libsoup/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig:/usr/local/opt/libosinfo/lib/pkgconfig:/usr/local/opt/libvirt/lib/pkgconfig:/usr/local/opt/libvirt-glib/lib/pkgconfig:/usr/local/opt/py3cairo/lib/pkgconfig:/usr/local/opt/gobject-introspection/lib/pkgconfig:/usr/local/opt/python@2/lib/pkgconfig:/usr/local/opt/py2cairo/lib/pkgconfig:/usr/local/opt/pygobject3/lib/pkgconfig:/usr/local/opt/gstreamer/lib/pkgconfig:/usr/local/opt/libogg/lib/pkgconfig:/usr/local/opt/libvorbis/lib/pkgconfig:/usr/local/opt/opus/lib/pkgconfig:/usr/local/opt/orc/lib/pkgconfig:/usr/local/opt/theora/lib/pkgconfig:/usr/local/opt/gst-plugins-base/lib/pkgconfig:/usr/local/opt/libmms/lib/pkgconfig:/usr/local/opt/gst-plugins-bad/lib/pkgconfig:/usr/local/opt/flac/lib/pkgconfig:/usr/local/opt/speex/lib/pkgconfig:/usr/local/opt/libshout/lib/pkgconfig:/usr/local/opt/libvpx/lib/pkgconfig:/usr/local/opt/taglib/lib/pkgconfig:/usr/local/opt/x264/lib/pkgconfig:/usr/local/opt/json-glib/lib/pkgconfig:/usr/local/opt/libusb/lib/pkgconfig:/usr/local/opt/lz4/lib/pkgconfig:/usr/local/opt/usbredir/lib/pkgconfig:/usr/local/opt/spice-gtk/lib/pkgconfig:/usr/local/opt/pcre2/lib/pkgconfig:/usr/local/opt/vte3/lib/pkgconfig:/usr/local/opt/adwaita-icon-theme/share/pkgconfig:/usr/local/opt/gsettings-desktop-schemas/share/pkgconfig:/usr/local/opt/yajl/share/pkgconfig:/usr/local/opt/spice-protocol/share/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.14
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
ACLOCAL_PATH: /usr/local/opt/gettext/share/aclocal:/usr/local/opt/libxml2/share/aclocal:/usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/intltool/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libpng/bin:/usr/local/opt/freetype/bin:/usr/local/opt/fontconfig/bin:/usr/local/opt/gettext/bin:/usr/local/opt/pcre/bin:/usr/local/opt/gdbm/bin:/usr/local/opt/openssl/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/xz/bin:/usr/local/opt/python/bin:/usr/local/opt/glib/bin:/usr/local/opt/cairo/bin:/usr/local/opt/jpeg/bin:/usr/local/opt/libtiff/bin:/usr/local/opt/gdk-pixbuf/bin:/usr/local/opt/libcroco/bin:/usr/local/opt/fribidi/bin:/usr/local/opt/graphite2/bin:/usr/local/opt/icu4c/bin:/usr/local/opt/harfbuzz/bin:/usr/local/opt/pango/bin:/usr/local/opt/librsvg/bin:/usr/local/opt/gtk+3/bin:/usr/local/opt/libtasn1/bin:/usr/local/opt/nettle/bin:/usr/local/opt/p11-kit/bin:/usr/local/opt/libevent/bin:/usr/local/opt/gnutls/bin:/usr/local/opt/libgpg-error/bin:/usr/local/opt/libgcrypt/bin:/usr/local/opt/gtk-vnc/bin:/usr/local/opt/check/bin:/usr/local/opt/libidn2/bin:/usr/local/opt/libpsl/bin:/usr/local/opt/webp/bin:/usr/local/opt/gd/bin:/usr/local/opt/jasper/bin:/usr/local/opt/netpbm/bin:/usr/local/opt/gts/bin:/usr/local/opt/libtool/bin:/usr/local/opt/graphviz/bin:/usr/local/opt/vala/bin:/usr/local/opt/libxml2/bin:/usr/local/opt/libosinfo/bin:/usr/local/opt/yajl/bin:/usr/local/opt/libvirt/bin:/usr/local/opt/gobject-introspection/bin:/usr/local/opt/python@2/bin:/usr/local/opt/gstreamer/bin:/usr/local/opt/orc/bin:/usr/local/opt/gst-plugins-base/bin:/usr/local/opt/faac/bin:/usr/local/opt/faad2/bin:/usr/local/opt/flac/bin:/usr/local/opt/taglib/bin:/usr/local/opt/lame/bin:/usr/local/opt/x264/bin:/usr/local/opt/json-glib/bin:/usr/local/opt/lz4/bin:/usr/local/opt/spice-gtk/bin:/usr/local/opt/pcre2/bin:/usr/local/opt/vte3/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by ssurfertuga** [comment]
I also have the exact same problem... 

`$ brew upgrade
==> Upgrading 1 outdated package:
jeffreywildman/virt-manager/virt-manager 2.1.0_3 -> 2.2.0
==> Upgrading jeffreywildman/virt-manager/virt-manager 
==> Downloading https://virt-manager.org/download/sources/virt-manager/virt-manager-2.2.0.tar.gz
Already downloaded: /Users/hugoramos/Library/Caches/Homebrew/downloads/65a6ce0513ace92277540efbdf5dd4810a2c10fcf32766f644a77d495b6f1554--virt-manager-2.2.0.tar.gz
==> Patching
patching file virt-manager
Hunk #1 succeeded at 170 (offset 19 lines).
==> Downloading https://files.pythonhosted.org/packages/37/27/706af3ee62032933a3217454609c50a5325a6bd9c2c2f495b58c456ba286/virtualenv-16.6.1.tar.gz
Already downloaded: /Users/hugoramos/Library/Caches/Homebrew/downloads/3c930834dac51edb05b7f34f88664cf348741680c6b1d860dc7ddc084d5b17eb--virtualenv-16.6.1.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/virt-manager--homebrew-virtualenv-20190711-41009-1a8cgyf/target --install-scripts=/private/tmp/virt-manager--homebrew-virtualenv-20190711-41009-1a8cgyf/target
==> python3 -s /private/tmp/virt-manager--homebrew-virtualenv-20190711-41009-1a8cgyf/target/bin/virtualenv -p python3 /usr/local/Cellar/virt-manager/2.2.0/libexec
==> Downloading https://libvirt.org/sources/python/libvirt-python-5.4.0.tar.gz
Already downloaded: /Users/hugoramos/Library/Caches/Homebrew/downloads/09d6a8a52d68070a63b6dada4a8a106d02aad0094ded04f15abddbe46d0ccda9--libvirt-python-5.4.0.tar.gz
==> /usr/local/Cellar/virt-manager/2.2.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/virt-manager--libvirt-python-20190711-41009-16veqjv/libvirt-python-5.4.0
Last 15 lines from /Users/hugoramos/Library/Logs/Homebrew/virt-manager/03.pip:
Removed build tracker '/private/tmp/pip-req-tracker-492wtow9'
ERROR: Command "/usr/local/Cellar/virt-manager/2.2.0/libexec/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/pip-req-build-d6asctil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-5bfk62ej/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/2.2.0/libexec/bin/../include/site/python3.7/libvirt-python" failed with error code 1 in /private/tmp/pip-req-build-d6asctil/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.2.0/libexec/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/virt-manager/2.2.0/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 414, in run
    use_user_site=options.use_user_site,
  File "/usr/local/Cellar/virt-manager/2.2.0/libexec/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/usr/local/Cellar/virt-manager/2.2.0/libexec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 951, in install
    spinner=spinner,
  File "/usr/local/Cellar/virt-manager/2.2.0/libexec/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/usr/local/Cellar/virt-manager/2.2.0/libexec/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/pip-req-build-d6asctil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-5bfk62ej/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/2.2.0/libexec/bin/../include/site/python3.7/libvirt-python" failed with error code 1 in /private/tmp/pip-req-build-d6asctil/`

Any ideas?

**Comment by ruria** [comment]
Me too!
