### ISSUE TITLE
Connecting over ssh works differently from inside virt-manager

### ISSUE THREAD

**Issue by aneurinprice** [jeffreywildman/homebrew-virt-manager#136]
When attempting to add a connection via the virt-manager interface, my ssh config seems to be ignored. SSH host entries and my ssh key do NOT appear to be acknowleged. Please see below.

<img width="1278" alt="Screenshot 2019-10-01 at 22 56 12" src="https://user-images.githubusercontent.com/46961848/66003713-c86c0980-e49e-11e9-8f87-10e579d35586.png">
<img width="1278" alt="Screenshot 2019-10-01 at 22 56 51" src="https://user-images.githubusercontent.com/46961848/66003714-c904a000-e49e-11e9-9cf5-dec561a80fb6.png">

If there is something I am misunderstanding how virt-manager works on macOS, please let me know. Perhaps there is a quick and easy fix by setting an env var that I do know about? This is 100% reproducable.

**Comment by aneurinprice** [comment]
@jeffreywildman I'm at a bit of a loss here, I don't know my way around a mac to troubleshoot this any further

**Comment by 5nafu** [comment]
@aneurinprice a possible workaround would be to add a connection with a `custom URI` from within virt-manager. Be sure to add the `socket` parameter as in your first example. This seems to have fixed the same issue I had on my machine.

**Comment by aneurinprice** [comment]
@5nafu  Thank you so much! I can confrim that this worked perfectly. Do you think I should keep the issue open as this is more of a workaround than a feature

**Comment by jeffreywildman** [comment]
Thanks @5nafu, closing since the issue will still remain searchable.
