### ISSUE TITLE
[Solved]Some issues happen when install virt-manger

### ISSUE THREAD

**Issue by 4O4n0tfound** [jeffreywildman/homebrew-virt-manager#164]
I am using "brew install virt-manager" to install virt-manger in my laptop, but some error info shows as below:
*******************************************************************************************************************
==> python3 -m venv /usr/local/Cellar/virt-manager/2.2.1_3/libexec
==> /usr/local/Cellar/virt-manager/2.2.1_3/libexec/bin/pip install -v --no-deps
Last 15 lines from /Users/myname/Library/Logs/Homebrew/virt-manager/02.pip:
  Found link https://files.pythonhosted.org/packages/59/64/4718738ffbc22d98b5223dbd6c5bb87c476d83a4c71719402935170064c7/pip-20.2.3.tar.gz#sha256=30c70b6179711a7c4cf76da89e8a0f5282279dfb0278bec7b94134be92543b6d (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.2.3
.......
Found link https://files.pythonhosted.org/packages/ca/1e/d91d7aae44d00cd5001957a1473e4e4b7d1d0f072d1af7c34b5899c9ccdf/pip-20.3.3.tar.gz#sha256=79c1ac8a9dccbec8752761cb5a2df833224263ca661477a2a9ed03ddf4e0e3ba (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.3.3
**Given no hashes to check 155 links for project 'pip': discarding no candidates
Removed build tracker: '/private/tmp/pip-req-tracker-c111q_42'**

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/jeffreywildman/homebrew-virt-manager/issues
*******************************************************************************************************************
I have no idea about this issues and what should i do next.
Is there anyone know how to solve it? I really appreciate~

**Comment by ruria** [comment]
Same here!

**Comment by colababy** [comment]
Same here, any idea?

**Comment by 4O4n0tfound** [comment]
I have no idea.  The point is that i even don`t know which part is incorrect.  Python or anything else........

**Comment by colababy** [comment]
changing libvirt-python 5.10.0 to 6.10.0 fixes this
in virt-manager.rb, replace libvirt-python resource like this
`
resource "libvirt-python" do
  url "https://libvirt.org/sources/python/libvirt-python-6.10.0.tar.gz"
  sha256 "47a8e90d9f49bc0296d2817f6009e18dbb69844ce10b81c2a2672bccd6f49fd5"
end
`

**Comment by ruria** [comment]
Thanks! It works

**Comment by 4O4n0tfound** [comment]
WoW, it works, i just change libvirt-pyhton 5.10.0 to 6.10.0, then i installs successfully.

Thank you all of your contrubutes, appreciate it.  :)
