### ISSUE TITLE
GLib-GIO-ERROR: No GSettings schemas are installed on the system

### ISSUE THREAD

**Issue by jokogr** [jeffreywildman/homebrew-virt-manager#168]
Hello,

I'm on a Intel MacBook Pro with Big Sur 11.2.3 and whenever I try to run `virt-manager` I get the following error:

```
❯ virt-manager

(virt-manager:37310): GLib-GIO-ERROR **: 11:32:55.294: No GSettings schemas are installed on the system
zsh: trace trap  virt-manager
```

Any ideas on how to fix it? I have already tried the following:

* Re-installing stuff, e.g.:

```
brew uninstall virt-manager virt-viewer
brew bundle dump; brew bundle --force cleanup
brew install virt-manager virt-viewer
```

* Applying the updates from #166, the installation was not working without bumping up libvirt-python to v7.1.0.

**Comment by jokogr** [comment]
Turns out that installing nix-darwin and home-manager affected some environment variables on my system: `XDG_DATA_DIRS` was set (or reset) and `/usr/local/share` was missing from there. As soon as I added this, virt-manager started working again.

**Comment by VergeDX** [comment]
Same issues here, thanks a lot! 😂
