### ISSUE TITLE
Brew install error with python 3.10

### ISSUE THREAD

**Issue by sergeeximius** [jeffreywildman/homebrew-virt-manager#192]
Hi
I have python version 3.10 installed (brew install python@3.10 && brew unlink python@3.9 && brew link python@3.10 && brew uninstall python@3.9). How do I install virt-viewer with this python version? Why does the package want 3.9? Where can I fix it for 3.10?
```
brew install virt-viewer
==> Downloading https://virt-manager.org/download/sources/virt-viewer/virt-viewer-8.0.tar.gz
Already downloaded: /Users/ssedov/Library/Caches/Homebrew/downloads/0daaa768f148a86e56367e58ce0e49c09df31344fa7aac0cbbd9446f4fb4be8c--virt-viewer-8.0.tar.gz
==> Installing virt-viewer from jeffreywildman/virt-manager
Error: An exception occurred within a child process:
  RuntimeError: /opt/homebrew/opt/python@3.9 not present or broken
Please reinstall python@3.9. Sorry :(
```

**Comment by cybit** [comment]
`brew edit virt-manager`
replace `depends on "python@3.9"` with `depends on "python@3.10"` ? 
If this will run into problems I don't know. 
But why did you uninstall python@3.9 ?

**Comment by sergeeximius** [comment]
Thanks for the reply. I got out of the situation and installed virt-viewer on my windows machine. I think your advice will help.
Python 3.10 installed to try out its new features, I'm interested in programming a little

**Comment by cybit** [comment]
@sergeeximius You might want to invest looking into pyenv then. Makes it easy to change the python version on the fly without breaking other stuff.
