### ISSUE TITLE
The post-install step did not complete successfully

### ISSUE THREAD

**Issue by mburgosh** [jeffreywildman/homebrew-virt-manager#22]
Hi,

I'm having some problems trying to install this formula. It seems the issue is in the postinstall phase.

> Failed executing: /usr/local/opt/gtk+/bin/gtk-update-icon-cache /usr/local/share/icons/hicolor
> /usr/local/Library/Homebrew/formula.rb:1289:in `block in system'
> /usr/local/Library/Homebrew/formula.rb:1246:in `open'
> /usr/local/Library/Homebrew/formula.rb:1246:in `system'
> /usr/local/Library/Taps/jeffreywildman/homebrew-virt-manager/virt-manager.rb:85:in `post_install'
> /usr/local/Library/Homebrew/formula.rb:750:in `run_post_install'
> /usr/local/Library/Homebrew/postinstall.rb:16:in `<main>'

`/usr/local/opt/gtk+/bin/gtk-update-icon-cache`  does not exist but `/usr/local/opt/gtk+3/bin/gtk3-update-icon-cache` does

**Comment by jeffreywildman** [comment]
Thanks for posting!  I've updated the post-install steps for both virt-manager and virt-viewer.  Let me know if this fixes things on your end.

**Comment by mburgosh** [comment]
Sorry for the delay, I needed to redo a clean install. New installs correctly :+1:

**Comment by jeffreywildman** [comment]
Thanks!  Closed by 3b5cbc9f814e9b9ec8f7f0c1595faab20d147a51.
