### ISSUE TITLE
ImportError: No module named gi

### ISSUE THREAD

**Issue by mrsmn** [jeffreywildman/homebrew-virt-manager#23]
```
  File "/usr/local/Cellar/virt-manager/1.2.1/libexec/share/virt-manager/virt-manager", line 29, in <module>
    import gi
ImportError: No module named gi
```

while trying:

```
function vm { virt-manager -c qemu+ssh://root@"$1"/system?socket=/var/run/libvirt/libvirt-sock; }
```

Using the lastest versions.

Cheers.

**Comment by mrsmn** [comment]
Fixed by running:

```
brew reinstall pygobject pygobject3
```

Cheers.

**Comment by jeffreywildman** [comment]
Hi, thanks for the report and fix.

Perhaps ```pygobject3``` was previously installed using a non-brewed Python before ```virt-manager``` was installed?  Under this scenario, ```pygobject3``` would be installed and technically satisfy the dependency of ```virt-manager```, but it would not be in the site-packages of the brewed Python.
