### ISSUE TITLE
El Capitan crashing troubles

### ISSUE THREAD

**Issue by Nethe** [jeffreywildman/homebrew-virt-manager#27]
Hello. 

I just updated my MAC into El Capitan and the virt-maganer still crashing. 
In the console, i can see this error:

`<
/usr/local/Cellar/virt-manager/1.2.1/libexec/share/virt-manager/virt-manager:31: PyGIWarning: LibvirtGLib was imported without specifying a version first. Use gi.require_version('LibvirtGLib', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import LibvirtGLib
/usr/local/Cellar/virt-manager/1.2.1/libexec/share/virt-manager/virtinst/osdict.py:26: PyGIWarning: Libosinfo was imported without specifying a version first. Use gi.require_version('Libosinfo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Libosinfo as libosinfo
🔥  Martin@hruska ~ $ 
(process:19457): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.>`

After i opened the settings of virtual hosts, i can see this in debug mode:

`<
[Thu, 15 Oct 2015 15:44:28 virt-manager 19687] DEBUG (sshtunnels:277) Generated tunnel fd=28 for viewer
[Thu, 15 Oct 2015 15:44:28 virt-manager 19687] DEBUG (sshtunnels:202) Opened tunnel PID=19694 ERRFD=26
[Thu, 15 Oct 2015 15:44:28 virt-manager 19687] DEBUG (viewers:336) Got credential request <enum VNC_DISPLAY_CREDENTIAL_PASSWORD of type VncDisplayCredential>
[Thu, 15 Oct 2015 15:44:28 virt-manager 19687] ERROR (keyring:61) Error determining keyring
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/1.2.1/libexec/share/virt-manager/virtManager/keyring.py", line 45, in __init__
    self._dbus = Gio.bus_get_sync(Gio.BusType.SESSION, None)
Error: g-spawn-exit-error-quark: Error spawning command line 'dbus-launch --autolaunch=f2e85730915d5334ee8fadd655f5b33a --binary-syntax --close-stderr': Child process exited with code 1 (1)
Segmentation fault: 11>`

It was working fine before the upgrade. Now, when i run the virt-manager, it is working until i press some button or move by mouse. Do you have same problem? 

Thanks, 
Nethe

**Comment by mlesin** [comment]
Confirming, have the same problem :(

**Comment by jeffreywildman** [comment]
Hi, I just updated my system to El Capitan (10.11.1).  While I am observing similar warnings/errors about LibVirtGlib and dbus-launch, I am still able to successfully interact with and use my test VM.  Additionally, I do not observe any output related to VNC credential requests and keyring tracebacks, even after switching between SPICE and VNC displays.

**Comment by Nethe** [comment]
So i don't know what to do. It is crashing on LibGlib error... May i try to remove and install this library? 
Please see this pastebin. The virt-manager workded perfectly before the upgrade...
http://pastebin.blesmrt.net/paifjseop/him0ao

**Comment by Nethe** [comment]
I upgraded the homebrew installed packages just now, and the virt-manager has started working. 
Maybe there was something wrong with glib library. 

Please close this issue. 
Thanks, 
Martin

**Comment by jeffreywildman** [comment]
Thanks for the update, closed.
