### ISSUE TITLE
authentication failed: unsupported authentication type 2

### ISSUE THREAD

**Issue by falfaro** [jeffreywildman/homebrew-virt-manager#29]
After having followed the instructions to get virt-manager installed, I get this weird error when trying to connect to a remote Red Hat Enterprise Linux 7.1 system over SSH:

$ virsh -c qemu+ssh://stack@esah-ostt-hv01p/system?socket=/var/run/libvirt/libvirt-sock 
error: failed to connect to the hypervisor
error: authentication failed: unsupported authentication type 2

I can't seem to get any further information from the client. Using "virt-manager" instead of "virsh":

$ virt-manager --debug
/usr/local/Cellar/virt-manager/1.2.1/libexec/share/virt-manager/virt-manager:31: PyGIWarning: LibvirtGLib was imported without specifying a version first. Use gi.require_version('LibvirtGLib', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import LibvirtGLib
/usr/local/Cellar/virt-manager/1.2.1/libexec/share/virt-manager/virtinst/osdict.py:26: PyGIWarning: Libosinfo was imported without specifying a version first. Use gi.require_version('Libosinfo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Libosinfo as libosinfo
[Wed, 04 Nov 2015 14:17:51 virt-manager 91602] DEBUG (cli:246) Launched with command line: /usr/local/Cellar/virt-manager/1.2.1/libexec/share/virt-manager/virt-manager --debug
[Wed, 04 Nov 2015 14:17:51 virt-manager 91602] DEBUG (virt-manager:153) virt-manager version: 1.2.1
[Wed, 04 Nov 2015 14:17:51 virt-manager 91602] DEBUG (virt-manager:154) virtManager import: <module 'virtManager' from '/usr/local/Cellar/virt-manager/1.2.1/libexec/share/virt-manager/virtManager/__init__.pyc'>

(process:91602): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
[Wed, 04 Nov 2015 14:17:51 virt-manager 91602] DEBUG (virt-manager:213) GTK version: 3.18.2
[Wed, 04 Nov 2015 14:17:51 virt-manager 91602] DEBUG (engine:456) libguestfs inspection support: False
[Wed, 04 Nov 2015 14:17:51 virt-manager 91602] DEBUG (systray:150) Showing systray: False
[Wed, 04 Nov 2015 14:17:51 virt-manager 91602] DEBUG (manager:207) Showing manager
[Wed, 04 Nov 2015 14:17:51 virt-manager 91602] DEBUG (engine:357) window counter incremented to 1
[Wed, 04 Nov 2015 14:17:52 virt-manager 91602] DEBUG (engine:188) Determining default libvirt URI
[Wed, 04 Nov 2015 14:17:52 virt-manager 91602] DEBUG (packageutils:39) No PackageKit packages to search for.
[Wed, 04 Nov 2015 14:17:56 virt-manager 91602] DEBUG (connect:104) Couldn't contact avahi: g-io-error-quark: Could not connect: No such file or directory (1)
[Wed, 04 Nov 2015 14:17:56 virt-manager 91602] DEBUG (connect:145) Showing open connection
[Wed, 04 Nov 2015 14:18:07 virt-manager 91602] DEBUG (connect:432) Generate URI=qemu+ssh://stack@esah-ostt-hv01p/system, auto=False
[Wed, 04 Nov 2015 14:18:07 virt-manager 91602] DEBUG (connect:134) Closing open connection
[Wed, 04 Nov 2015 14:18:07 virt-manager 91602] DEBUG (connection:536) conn=qemu+ssh://stack@esah-ostt-hv01p/system changed to state=Connecting
[Wed, 04 Nov 2015 14:18:07 virt-manager 91602] DEBUG (connection:846) Scheduling background open thread for qemu+ssh://stack@esah-ostt-hv01p/system
[Wed, 04 Nov 2015 14:18:07 virt-manager 91602] DEBUG (connection:536) conn=qemu+ssh://stack@esah-ostt-hv01p/system changed to state=Disconnected
[Wed, 04 Nov 2015 14:18:07 virt-manager 91602] DEBUG (engine:597) connect_error: conn transport=ssh
[Wed, 04 Nov 2015 14:18:07 virt-manager 91602] DEBUG (error:97) error dialog message:
summary=Unable to connect to libvirt.

internal error: received hangup / error event on socket

Verify that the 'libvirtd' daemon is running
on the remote host.

Would you still like to remember this connection?
details=Unable to connect to libvirt.

internal error: received hangup / error event on socket

Verify that the 'libvirtd' daemon is running
on the remote host.

Libvirt URI is: qemu+ssh://stack@esah-ostt-hv01p/system

Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/1.2.1/libexec/share/virt-manager/virtManager/connection.py", line 862, in _do_open
    self._backend.open(self._do_creds_password)
  File "/usr/local/Cellar/virt-manager/1.2.1/libexec/share/virt-manager/virtinst/connection.py", line 161, in open
    open_flags)
  File "/usr/local/Cellar/virt-manager/1.2.1/libexec/vendor/lib/python2.7/site-packages/libvirt.py", line 106, in openAuth
    raise libvirtError('virConnectOpenAuth() failed')
libvirtError: internal error: received hangup / error event on socket
[Wed, 04 Nov 2015 14:18:36 virt-manager 91602] DEBUG (connect:145) Showing open connection

Any ideas?

**Comment by jeffreywildman** [comment]
Hey, check out this [link](http://libvirt.org/guide/html/Application_Development_Guide-Connections-Debug.html) for debugging options that may help.

**Comment by jeffreywildman** [comment]
It doesn't look like a solution, but similar issues:

https://www.redhat.com/archives/libvirt-users/2013-March/msg00060.html
https://www.redhat.com/archives/libvirt-users/2013-March/msg00074.html

Since this is happening with virsh, it seems to be an issue outside of the virt-manager recipes.  Sorry I don't have a solution for you, closing for now.
