### ISSUE TITLE
Download does not work

### ISSUE THREAD

**Issue by Philelis** [jeffreywildman/homebrew-virt-manager#32]
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "virt-manager"
Download failed: https://virt-manager.org/download/sources/virt-manager/virt-manager-1.2.1.tar.gz

**Comment by akshaysth** [comment]
I'm receiving the same error. It seems to be a problem upstream with virt-manager's file hosting. Is it possible to switch to using their git releases?

**Comment by b33j0r** [comment]
I was able to get past this step by changing the url to `https://github.com/virt-manager/virt-manager/archive/v1.2.1.tar.gz` and updating the SHA. But now I'm seeing a similar issue with `virt-viewer` and that approach doesn't work. https://github.com/b33j0r/homebrew-virt-manager/commit/ea3fdbe0f55d21f74405ef6875f6a70ec376f893

**Comment by zzoru** [comment]
virt-viewer: https://fedorahosted.org/released/virt-viewer/virt-viewer-2.0.tar.gz

**Comment by jeffreywildman** [comment]
Hi, this might be related to a new version of virt-manager (1.3.0) being released.  I've updated the urls for both virt-manager and virt-viewer from virt-manager.org to fedorahosted.org in a3c153674014d7177c83bcf978bf55b70c1e871c.  This leaves the sha256 sums unchanged for the formula's current versions.

**Comment by Philelis** [comment]
$ brew install virt-viewer
==> Installing virt-viewer from jeffreywildman/homebrew-virt-manager
==> Downloading https://fedorahosted.org/released/virt-viewer/virt-viewer-2.0.ta
Already downloaded: /Library/Caches/Homebrew/virt-viewer-2.0.tar.gz
Error: SHA256 mismatch
Expected: e9c583bcb5acdabac6a8a13eff6ce4e093a3050645771628f832e15ce685d437
Actual: 2aeb08d1ec53c4c9d8d3e4b8a8d43bdb011e20a1d746fec95f4f835b8cd85980
Archive: /Library/Caches/Homebrew/virt-viewer-2.0.tar.gz
To retry an incomplete download, remove the file above.

It is not the same SHA256 sum for virt-viewer. For virt-manager I don't know, because I have already installed it.

**Comment by jeffreywildman** [comment]
jeffw@fuji in ~/Downloads
$ wget https://fedorahosted.org/released/virt-viewer/virt-viewer-2.0.tar.gz
--2015-11-25 14:26:40--  https://fedorahosted.org/released/virt-viewer/virt-viewer-2.0.tar.gz
Resolving fedorahosted.org (fedorahosted.org)... 140.211.169.199
Connecting to fedorahosted.org (fedorahosted.org)|140.211.169.199|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Date: Wed, 25 Nov 2015 20:26:39 GMT
  Server: Apache/2.2.15 (Red Hat)
  Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
  Last-Modified: Mon, 12 Jan 2015 17:58:02 GMT
  ETag: "2c110c-bc722-50c783f5cbc28"
  Accept-Ranges: bytes
  Content-Length: 771874
  Keep-Alive: timeout=5, max=500
  Connection: Keep-Alive
  Content-Type: application/x-gzip
Length: 771874 (754K) [application/x-gzip]
Saving to: 'virt-viewer-2.0.tar.gz'

virt-viewer-2.0.tar.gz        100%[=================================================>] 753.78K   580KB/s   in 1.3s   

2015-11-25 14:26:41 (580 KB/s) - 'virt-viewer-2.0.tar.gz' saved [771874/771874]

jeffw@fuji in ~/Downloads
$ sha256sum virt-viewer-2.0.tar.gz 
e9c583bcb5acdabac6a8a13eff6ce4e093a3050645771628f832e15ce685d437  virt-viewer-2.0.tar.gz

**Comment by jeffreywildman** [comment]
See above, the checksum in the formula is correct.  When running ```brew install virt-viewer```, your virt-viewer from github is being cached and is not being redownloaded from fedorahosted.org.  Try deleting the cached virt-viewer from ```/Library/Caches/Homebrew/``` and reinstalling.

**Comment by Philelis** [comment]
Ah thanks, works.
