### ISSUE TITLE
Error connecting to graphical console: could not get a reference to type class

### ISSUE THREAD

**Issue by irobayna** [jeffreywildman/homebrew-virt-manager#39]
I got two computers with this ```awesome``` package installed, on one I did a ```brew update & brew upgrade``` and when I connect to the VMs and try to view the console, I get this error.  On the other computer which has not been updated, the console works as expected.

**Comment by alhafoudh** [comment]
+1

**Comment by ne4u** [comment]
this fixed it for me:
brew uninstall --force gtk+3 libvirt-glib gtk-vnc spice-gtk libvirt pygobject3 virt-manager virt-viewer && brew install virt-manager virt-viewer

**Comment by jeffreywildman** [comment]
Thanks for the note @ne4u. I'll add a note in the FAQ on the mainpage.
