### ISSUE TITLE
No connection available for qemu:///system

### ISSUE THREAD

**Issue by lukkamor** [jeffreywildman/homebrew-virt-manager#41]
Hi, just installed vert-manager/virt-viewer on my mac os with El Capitan.
I am able to connect to remote libvirtds with no problems.
But I cannot make libvirtd work inside my mac.
when libvirtd started as:

/usr/local/Cellar/libvirt/1.3.2/sbin/libvirtd --daemon --verbose

I get this error:

libvirt[90470]: 18446744073709551615: error : do_open:1085 : no connection driver available for qemu:///system

Also if I use vert-manager or virsh, I get the same error:

virt-manager --debug -c qemu:///system?socket=/usr/local/var/run/libvirt/libvirt-sock
[Thu, 31 Mar 2016 18:24:49 virt-manager 89901] DEBUG (cli:256) Launched with command line: /usr/local/Cellar/virt-manager/1.3.2/libexec/share/virt-manager/virt-manager --debug -c qemu:///system?socket=/usr/local/var/run/libvirt/libvirt-sock
[Thu, 31 Mar 2016 18:24:49 virt-manager 89901] DEBUG (virt-manager:143) virt-manager version: 1.3.2
[Thu, 31 Mar 2016 18:24:49 virt-manager 89901] DEBUG (virt-manager:144) virtManager import: <module 'virtManager' from '/usr/local/Cellar/virt-manager/1.3.2/libexec/share/virt-manager/virtManager/__init__.pyc'>
[Thu, 31 Mar 2016 18:24:49 virt-manager 89901] DEBUG (virt-manager:203) GTK version: 3.18.9
[Thu, 31 Mar 2016 18:24:49 virt-manager 89901] DEBUG (engine:496) libguestfs inspection support: False
[Thu, 31 Mar 2016 18:24:49 virt-manager 89901] DEBUG (systray:154) Showing systray: False
[Thu, 31 Mar 2016 18:24:49 virt-manager 89901] DEBUG (engine:1028) processing cli command uri=qemu:///system?socket=/usr/local/var/run/libvirt/libvirt-sock show_window= domain=
[Thu, 31 Mar 2016 18:24:49 virt-manager 89901] DEBUG (manager:203) Showing manager
[Thu, 31 Mar 2016 18:24:49 virt-manager 89901] DEBUG (engine:401) window counter incremented to 1
[Thu, 31 Mar 2016 18:24:49 virt-manager 89901] DEBUG (engine:161) Loading stored URIs:
qemu:///system?socket=/usr/local/var/run/libvirt/libvirt-sock
[Thu, 31 Mar 2016 18:24:49 virt-manager 89901] DEBUG (engine:140) Initial gtkapplication activated
[Thu, 31 Mar 2016 18:24:49 virt-manager 89901] DEBUG (connection:568) conn=qemu:///system?socket=/usr/local/var/run/libvirt/libvirt-sock changed to state=Connecting
[Thu, 31 Mar 2016 18:24:49 virt-manager 89901] DEBUG (connection:887) Scheduling background open thread for qemu:///system?socket=/usr/local/var/run/libvirt/libvirt-sock
uri: qemu:///system?socket=/usr/local/var/run/libvirt/libvirt-sock auth: [[2, 5], <bound method VirtualConnection._auth_cb of <virtinst.connection.VirtualConnection object at 0x1100e3c10>>, (<bound method vmmConnection._do_creds_password of <vmmConnection object at 0x1100e7eb0 (virtManager+connection+vmmConnection at 0x7fb4fe126740)>>, [2, 5])] ret: None
[Thu, 31 Mar 2016 18:24:49 virt-manager 89901] DEBUG (connection:568) conn=qemu:///system?socket=/usr/local/var/run/libvirt/libvirt-sock changed to state=Disconnected
[Thu, 31 Mar 2016 18:24:49 virt-manager 89901] DEBUG (error:99) error dialog message:
summary=Unable to connect to libvirt.

no connection driver available for qemu:///system
details=Unable to connect to libvirt.

no connection driver available for qemu:///system

Libvirt URI is: qemu:///system?socket=/usr/local/var/run/libvirt/libvirt-sock

Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/1.3.2/libexec/share/virt-manager/virtManager/connection.py", line 903, in _do_open
    self._backend.open(self._do_creds_password)
  File "/usr/local/Cellar/virt-manager/1.3.2/libexec/share/virt-manager/virtinst/connection.py", line 148, in open
    open_flags)
  File "/usr/local/Cellar/virt-manager/1.3.2/libexec/vendor/lib/python2.7/site-packages/libvirt.py", line 106, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirtError: no connection driver available for qemu:///system
[Thu, 31 Mar 2016 18:24:50 virt-manager 89901] DEBUG (engine:225) Determining default libvirt URI
=========================================================================

any ideas?
I have installed qemu via homebrew :
brew install qemu

I was able to run qemu...

i am the administrator user and tried to run with sudo having the same problem.

**Comment by jeffreywildman** [comment]
Unfortunately, I have not connected `virt-manager` to local hypervisors on OSX. It seems most users, including myself, use these formulae to remotely manage hypervisors on non-OSX systems. I'll be including a note in the FAQ. If you make progress and would like to share the details, please do.

**Comment by cutoutsy** [comment]
I also have the problem when i use these formulae to remotely manage hypervisors on non-OSX systems.
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/1.3.2/libexec/share/virt-manager/virtManager/connection.py", line 903, in _do_open
    self._backend.open(self._do_creds_password)
  File "/usr/local/Cellar/virt-manager/1.3.2/libexec/share/virt-manager/virtinst/connection.py", line 148, in open
    open_flags)
  File "/usr/local/Cellar/virt-manager/1.3.2/libexec/vendor/lib/python2.7/site-packages/libvirt.py", line 105, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirtError: An error occurred, but the cause is unknown

and when i run:
virt-manager --no-fork -c qemu+ssh://xxx@xxx/system?socket=/var/run/libvirt/libvirt-sock
I get the error:
zsh: no matches found: qemu+ssh://xxx@xxx/system?socket=/var/run/libvirt/libvirt-sock

what is wrong?

**Comment by junkblocker** [comment]
@cutoutsy, zsh is interpreting ``@`` and ``?`` etc. as special characters.

Try 

```sh
virt-manager --no-fork -c 'qemu+ssh://xxx@xxx/system?socket=/var/run/libvirt/libvirt-sock'
```

**Comment by cutoutsy** [comment]
@junkblocker 
yes, I find the problem in the issues,thank you anyway.

**Comment by publicarray** [comment]
https://github.com/Homebrew/homebrew-core/pull/32820 fixes OPs (@lukkamor's) issue.
