### ISSUE TITLE
Problem Installing

### ISSUE THREAD

**Issue by vamem9z-Moses** [jeffreywildman/homebrew-virt-manager#43]
I tried installing earlier today. virt-viewer installs with no problem. Here's what I got with virt-manager. The dependencies installed correctly the first time I tried to install it. 

brew doctor
Your system is ready to brew.
 ~  brew install virt-manager
==> Installing virt-manager from jeffreywildman/virt-manager
==> Installing dependencies for jeffreywildman/virt-manager/virt-manager:
==> Installing jeffreywildman/virt-manager/virt-manager dependency: libgc
==> Downloading https://homebrew.bintray.com/bottles/libgcrypt-1.7.0.el_capitan.
######################################################################## 100.0%
==> Pouring libgcrypt-1.7.0.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/libgcrypt/1.7.0: 17 files, 1.5M
==> Installing jeffreywildman/virt-manager/virt-manager
==> Downloading https://fedorahosted.org/released/virt-manager/virt-manager-1.3.
Already downloaded: /Library/Caches/Homebrew/virt-manager-1.3.2.tar.gz
==> Patching
patching file virt-clone
patching file virt-convert
patching file virt-install
patching file virt-manager
patching file virt-xml
==> Downloading https://libvirt.org/sources/python/libvirt-python-1.3.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/virt-manager--libvirt-python-1.3.2.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cel
Last 15 lines from /Users/mmiles/Library/Logs/Homebrew/virt-manager/01.python:
--record=installed.txt

running install
running build
/usr/local/opt/pkg-config/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
/usr/local/opt/python/bin/python2.7 generator.py libvirt /usr/local/Cellar/libvirt/1.3.3/share/libvirt/api/libvirt-api.xml
Found 409 functions in /usr/local/Cellar/libvirt/1.3.3/share/libvirt/api/libvirt-api.xml
Found 0 functions in libvirt-override-api.xml
Generated 339 wrapper functions
Missing type converters:
virTypedParameterPtr:1
virTypedParameterPtr *:1
ERROR: failed virDomainGetPerfEvents
ERROR: failed virDomainSetPerfEvents
error: command '/usr/local/opt/python/bin/python2.7' failed with exit status 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/jeffreywildman/homebrew-virt-manager/issues

**Comment by jeffreywildman** [comment]
Thanks, I can reproduce the error on my system. I've updated dependency ```libvirt-python``` to 1.3.3, which should take care of this. When you have an opportunity, please confirm.

**Comment by vamem9z-Moses** [comment]
It installs now. Thanks.
