### ISSUE TITLE
Can't install libvirt-python on El Capitan

### ISSUE THREAD

**Issue by pavelz** [jeffreywildman/homebrew-virt-manager#50]
==> Installing virt-manager from jeffreywildman/virt-manager
==> Downloading https://fedorahosted.org/released/virt-manager/virt-manager-1.4.0.tar.gz
Already downloaded: /Users/pavel/Library/Caches/Homebrew/virt-manager-1.4.0.tar.gz
==> Patching
patching file virt-clone
patching file virt-convert
patching file virt-install
patching file virt-manager
patching file virt-xml
==> Downloading https://libvirt.org/sources/python/libvirt-python-1.3.5.tar.gz
Already downloaded: /Users/pavel/Library/Caches/Homebrew/virt-manager--libvirt-python-1.3.5.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/virt-manager/1.4.0/libexec/vendor --single-version-externally-managed --record=installed.txt
Last 15 lines from /Users/pavel/Library/Logs/Homebrew/virt-manager/01.python:
--record=installed.txt

running install
running build
/usr/local/opt/pkg-config/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
/usr/local/opt/python/bin/python2.7 generator.py libvirt /usr/local/Cellar/libvirt/2.0.0/share/libvirt/api/libvirt-api.xml
Found 413 functions in /usr/local/Cellar/libvirt/2.0.0/share/libvirt/api/libvirt-api.xml
Found 0 functions in libvirt-override-api.xml
Generated 343 wrapper functions
Missing type converters:
virTypedParameterPtr *:1
virConnectStoragePoolEventGenericCallback:1
ERROR: failed virConnectStoragePoolEventRegisterAny
ERROR: failed virDomainGetGuestVcpus
error: command '/usr/local/opt/python/bin/python2.7' failed with exit status 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/jeffreywildman/homebrew-virt-manager/issues

**Comment by jessiebryan** [comment]
I'm also having this issue today.

**Comment by pavelz** [comment]
i have tried to use it with libvirt-python-2.0.0, it installs and runs but gives a cryptic message on trying to connect to qemu+ssh host.

**Comment by chrootLogin** [comment]
same error here.

**Comment by techdev5521** [comment]
Bump

**Comment by aussieade** [comment]
just encountered this too

**Comment by alexrett** [comment]
same error

**Comment by mgraff** [comment]
Same issue here

**Comment by Marzelpan** [comment]
Works for me with libvirt-python-2.1.0

**Comment by bryanlharris** [comment]
Same here

**Comment by shurilnik** [comment]
Marzelpan, could you please provide the way to use libvirt-python-2.1.0 ? As it forcibly downloads https://libvirt.org/sources/python/libvirt-python-1.3.5.tar.gz

**Comment by Marzelpan** [comment]
Hi! I patched virt-manager.rb just like leafi did in pull request #53. #

**Comment by mgraff** [comment]
Until the pull request is accepted, you have to manually patch the file `/usr/local/Library/Taps/jeffreywildman/homebrew-virt-manager/virt-manager.rb` with the following diff, then brew install virt-manager

     -    url "https://libvirt.org/sources/python/libvirt-python-1.3.5.tar.gz"
     -    sha256 "a0508a57637fd18a3584fb9d2322fb172f65708c9db16e0438a70eb0f36fa5c2"
     +    url "https://libvirt.org/sources/python/libvirt-python-2.1.0.tar.gz"
     +    sha256 "74887fa1be60db2701e726da7e01e3bf18ecd3b8d1cfdf2f1f7480e1a1edbacb"

**Comment by shurilnik** [comment]
Thank you! Got it! ;-)

**Comment by jnix85** [comment]
Could someone provide newb instructions for patching this? I am a recent linux convert

**Comment by jeffreywildman** [comment]
Closing as this was likely due to mismatch between libvirt-python and libvirt version. Updated virt-manager points to libvirt-4.0.0 to match latest libvirt in homebrew-core.
