### ISSUE TITLE
after brew update  , the same error

### ISSUE THREAD

**Issue by huof6829** [jeffreywildman/homebrew-virt-manager#55]
brew install virt-manager
==> Installing virt-manager from jeffreywildman/virt-manager
==> Installing dependencies for jeffreywildman/virt-manager/virt-manager: libtiff, libpng, freetype, fontconfig, pixman, cairo, gobject-introspection, gdk-pixbuf, atk, libepoxy, icu4c, harfbuzz, pango, hicolor-icon-theme, gsettings-desktop-schemas, gtk+3, libtasn1, gmp, nettle, gnutls, libgpg-error, libgcrypt, gtk-vnc, check, glib-networking, sqlite, vala, libsoup, libxml2, py2cairo, pygobject3, libosinfo, yajl, libvirt, libvirt-glib, libtool, spice-protocol, usbredir, spice-gtk, vte3
==> Installing jeffreywildman/virt-manager/virt-manager dependency: libtiff
==> Using the sandbox
==> Downloading http://download.osgeo.org/libtiff/tiff-4.0.6.tar.gz
Already downloaded: /var/root/Library/Caches/Homebrew/libtiff-4.0.6.tar.gz
==> Downloading https://mirrors.ocf.berkeley.edu/debian/pool/main/t/tiff/tiff_4.0.6-2.debian.tar.xz

curl: (35) SSL certificate problem: Couldn't understand the server certificate format
Trying a mirror...
==> Downloading https://mirrorservice.org/sites/ftp.debian.org/debian/pool/main/t/tiff/tiff_4.0.6-2.debian.tar.xz

curl: (35) SSL certificate problem: Couldn't understand the server certificate format
Error: Failed to download resource "libtiff--patch"
Download failed: https://mirrorservice.org/sites/ftp.debian.org/debian/pool/main/t/tiff/tiff_4.0.6-2.debian.tar.xz

please how to resolve?
my system is mac os EI Capitan

**Comment by jeffreywildman** [comment]
I would suggest trying to install libtiff separately with (`brew install libtiff`), but would recommend bringing the issue up with homebrew-core since that is where the formula resides.
