### ISSUE TITLE
Error installing spice-gtk: No package 'spice-client-glib-2.0' found

### ISSUE THREAD

**Issue by GioMac** [jeffreywildman/homebrew-virt-manager#56]
So, here it is:
`==> Installing jeffreywildman/virt-manager/virt-viewer dependency: spice-gtk
==> Downloading http://www.spice-space.org/download/gtk/spice-gtk-0.31.tar.bz2
Already downloaded: /Users/giomac/Library/Caches/Homebrew/spice-gtk-0.31.tar.bz2
==> ./configure --disable-silent-rules --with-gtk=3.0 --enable-introspection --enable-vala --with-audio=no --with-coroutine=gthread --prefix=/usr/local/Cellar/spice-gtk/0.31
==> make install
Last 15 lines from /Users/giomac/Library/Logs/Homebrew/spice-gtk/02.make:
CPPFLAGS="" CFLAGS="-g -O2" LDFLAGS="" CC="clang" PKG_CONFIG="/usr/local/opt/pkg-config/bin/pkg-config" DLLTOOL="false"  /usr/local/Cellar/gobject-introspection/1.48.0/bin/g-ir-scanner  --warn-all --accept-unprefixed --add-include-path=. --symbol-prefix=spice --identifier-prefix=Spice --namespace=SpiceClientGtk --nsversion=3.0 --libtool="/bin/sh ../libtool"  --include=GObject-2.0 --include=Gtk-3.0 --include=SpiceClientGLib-2.0 --pkg-export=spice-client-gtk-3.0  --library=libspice-client-gtk-3.0.la --library=libspice-client-glib-2.0.la --c-include="spice-widget.h" --cflags-begin -DSPICE_COMPILATION -DG_LOG_DOMAIN=\"GSpice\" -DSPICE_NO_DEPRECATED -DSPICE_GTK_LOCALEDIR=\"/usr/local/Cellar/spice-gtk/0.31/share/locale\" -DPNP_IDS=\""/pnp.ids"\" -DUSB_IDS=\"""\" -DSPICE_DISABLE_ABORT -I.. -I ../spice-common/ -I/usr/local/Cellar/spice-protocol/0.12.12/include/spice-1 -I/usr/local/Cellar/pixman/0.34.0/include/pixman-1  -D_REENTRANT -I/usr/local/Cellar/libpng/1.6.24/include/libpng16 -I/usr/local/Cellar/freetype/2.6.5/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.1/include -I/usr/local/Cellar/freetype/2.6.5/include/freetype2 -I/usr/local/Cellar/pixman/0.34.0/include/pixman-1 -I/usr/local/Cellar/pcre/8.39/include -I/usr/local/Cellar/glib/2.48.1/include/gio-unix-2.0/ -I/usr/local/Cellar/glib/2.48.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.48.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/cairo/1.14.6_1/include/cairo -I/usr/local/Cellar/gdk-pixbuf/2.34.0/include/gdk-pixbuf-2.0 -I/usr/local/Cellar/atk/2.20.0/include/atk-1.0 -I/usr/local/Cellar/libepoxy/1.3.1/include -I/usr/local/Cellar/harfbuzz/1.3.0/include/harfbuzz -I/usr/local/Cellar/pango/1.40.2/include/pango-1.0 -I/usr/local/Cellar/gtk+3/3.20.6/include/gtk-3.0 -I/usr/local/Cellar/libpng/1.6.24/include/libpng16 -I/usr/local/Cellar/freetype/2.6.5/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.1/include -I/usr/local/Cellar/freetype/2.6.5/include/freetype2 -I/usr/local/Cellar/pixman/0.34.0/include/pixman-1 -I/usr/local/Cellar/pcre/8.39/include -I/usr/local/Cellar/glib/2.48.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.48.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/cairo/1.14.6_1/include/cairo -I/usr/local/Cellar/pcre/8.39/include -I/usr/local/Cellar/glib/2.48.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.48.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -D_REENTRANT -I/usr/local/Cellar/pcre/8.39/include -I/usr/local/Cellar/glib/2.48.1/include/gio-unix-2.0/ -I/usr/local/Cellar/glib/2.48.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.48.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.39/include -I/usr/local/Cellar/glib/2.48.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.48.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/openssl/1.0.2h_1/include    -I/usr/local/Cellar/libusb/1.0.20/include/libusb-1.0 -I/usr/local/Cellar/usbredir/0.7.1/include      --cflags-end  spice-client-gtk.h spice-gtk-session.h spice-widget.h spice-grabsequence.h usb-device-widget.h spice-widget-enums.h spice-gtk-session.c spice-widget.c spice-grabsequence.c usb-device-widget.c libspice-client-gtk-3.0.la SpiceClientGLib-2.0.gir --output SpiceClientGtk-3.0.gir
Package spice-client-glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing`spice-client-glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'spice-client-glib-2.0' found
g-ir-scanner: link: /bin/sh ../libtool --mode=link --tag=CC clang -o /private/tmp/spice-gtk-20160903-88323-vnd9c9/spice-gtk-0.31/src/tmp-introspectsxrRWK/SpiceClientGtk-3.0 -export-dynamic -g -O2 tmp-introspectsxrRWK/private/tmp/spice-gtk-20160903-88323-vnd9c9/spice-gtk-0.31/src/tmp-introspectsxrRWK/SpiceClientGtk-3.0.o -L. libspice-client-gtk-3.0.la libspice-client-glib-2.0.la -L/usr/local/Cellar/glib/2.48.1/lib -L/usr/local/opt/gettext/lib -lgio-2.0 -lgobject-2.0 -lgmodule-2.0 -lglib-2.0 -lintl
libtool: link: clang -o /private/tmp/spice-gtk-20160903-88323-vnd9c9/spice-gtk-0.31/src/tmp-introspectsxrRWK/.libs/SpiceClientGtk-3.0 -g -O2 tmp-introspectsxrRWK/private/tmp/spice-gtk-20160903-88323-vnd9c9/spice-gtk-0.31/src/tmp-introspectsxrRWK/SpiceClientGtk-3.0.o  -L. ./.libs/libspice-client-gtk-3.0.dylib -L/usr/local/Cellar/pixman/0.34.0/lib -L/usr/local/Cellar/glib/2.48.1/lib -L/usr/local/opt/gettext/lib -L/usr/local/Cellar/openssl/1.0.2h_1/lib -L/usr/local/Cellar/libusb/1.0.20/lib -L/usr/local/Cellar/usbredir/0.7.1/lib -L/usr/local/Cellar/cairo/1.14.6_1/lib -L/usr/local/Cellar/gdk-pixbuf/2.34.0/lib -L/usr/local/Cellar/atk/2.20.0/lib -L/usr/local/Cellar/pango/1.40.2/lib -L/usr/local/Cellar/gtk+3/3.20.6/lib -L/usr/local/Cellar/libepoxy/1.3.1/lib /private/tmp/spice-gtk-20160903-88323-vnd9c9/spice-gtk-0.31/src/.libs/libspice-client-glib-2.0.dylib -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lgdk_pixbuf-2.0 -lcairo -lepoxy ./.libs/libspice-client-glib-2.0.dylib -ljpeg -lz -lpixman-1 -lssl -lcrypto -lusb-1.0 -lusbredirhost -lusbredirparser -lgthread-2.0 -lgio-2.0 -lgobject-2.0 -lgmodule-2.0 -lglib-2.0 -lintl
/usr/local/Cellar/gobject-introspection/1.48.0/bin/g-ir-compiler --includedir=. --includedir=. SpiceClientGtk-3.0.gir -o SpiceClientGtk-3.0.typelib
Could not find GIR file 'Gtk-3.0.gir'; check XDG_DATA_DIRS or use --includedir
error parsing file SpiceClientGtk-3.0.gir: Failed to parse included gir Gtk-3.0
make[4]: **\* [SpiceClientGtk-3.0.typelib] Error 1
make[3]: **\* [install-recursive] Error 1
make[2]: **\* [install] Error 2
make[1]: **\* [install-recursive] Error 1
make: **\* [install] Error 2`

**Comment by vans163** [comment]
ditto

**Comment by mlanner** [comment]
+1

**Comment by maxxer** [comment]
I had this same error. Then I noticed some brew messages during upgrade:
```
Error: You must `brew link glib fontconfig pixman cairo gobject-introspection` before harfbuzz can be installed
Error: You must `brew link libtasn1 nettle gnutls` before libvirt can be installed
```

After executing the second command I was able to install virt-manager. (buy sadly I'm now getting an error on /usr/local/opt/glib/lib/libglib-2.0.0.dylib while trying to run it)

**Comment by techana** [comment]
The same thing here! On macOS Heigh sierra:

> make[4]: *** [SpiceClientGtk-3.0.gir] Error 1
> make[3]: *** [install-recursive] Error 1
> make[2]: *** [install] Error 2
> make[1]: *** [install-recursive] Error 1
> make: *** [install] Error 2

**Comment by jeffreywildman** [comment]
spice-gtk was recenbtly updated to 0.34 via pull requests #83. Closing this issue, please open a new issue if a fresh install of spice-gtk `brew install spice-gtk` fails.
