### ISSUE TITLE
Offical Macos Sierra Support

### ISSUE THREAD

**Issue by ki-media** [jeffreywildman/homebrew-virt-manager#59]
There is still the message:

"Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages."

It still does build failures and requires workarounds which doesn´t work for all.. In fact Macos Sierra isn´t a pre-release anymore, I think we should make an Issue about that.

**Comment by shilov** [comment]
Would be nice to have this working in Sierra.

**Comment by jeffreywildman** [comment]
It's not clear what was generating the error message provided above, sounds like it was an issue with Homebrew itself. virt-manager formula is installing and running on macOS Sierra.
