### ISSUE TITLE
Support for system-brewed python

### ISSUE THREAD

**Issue by jeffreywildman** [jeffreywildman/homebrew-virt-manager#6]
Formulas currently assume brewed python.

**Comment by mrsmn** [comment]
Hi there,

have you made any progress on this?

Cheers.

**Comment by jeffreywildman** [comment]
Hi, I think I have something working on a dev branch with commit d4ec680496e2d750a8d544c37304cea23ace5214.  It should use the system python (or the python that is first in the user's path), as recommended by this [guide](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Python-for-Formula-Authors.md#python-declarations).

I've tested it on 10.11.1 with a complete reinstall of homebrew packages using the system python managed by ```pyenv```.  If you have a moment to test it out, let me know if it works for you and which python you used.

**Comment by jeffreywildman** [comment]
I'm reasonably confident that the OSX system python will work fine with the formulas.  Please open new issues as they are encountered.
