### ISSUE TITLE
Create new virtual machine OS types missing

### ISSUE THREAD

**Issue by karlfehd** [jeffreywildman/homebrew-virt-manager#64]
After a brew update a few weeks ago myself and several co-workers can no longer create new virtual machines because the OS type drop down box no longer populates with any choices.  It seems like it's pointing to an out of date library or something.

<img width="397" alt="screen shot 2016-12-02 at 2 16 30 pm" src="https://cloud.githubusercontent.com/assets/5270201/20846947/f76fec94-b899-11e6-80f3-bd132424f8bc.png">

**Comment by cmsimike** [comment]
It has magically fixed itself for me. Not sure why

**Comment by karlfehd** [comment]
My guess is it might have something to do with the dependancies in brew.  When I run `brew info virt-manager` I get the following:
`jeffreywildman/virt-manager/virt-manager: stable 1.4.0
App for managing virtual machines
https://virt-manager.org/
/usr/local/Cellar/virt-manager/1.4.0 (534 files, 12.8M) *
  Built from source on 2016-11-18 at 08:55:24
From: https://github.com/jeffreywildman/homebrew-virt-manager/blob/master/virt-manager.rb
==> Dependencies
Build: intltool ✔, pkg-config ✔
Required: dbus ✔, gnome-icon-theme ✔, gtk+3 ✘, gtk-vnc ✔, hicolor-icon-theme ✔, libosinfo ✔, libvirt ✔, libvirt-glib ✔, libxml2 --with-python ✔, pygobject3 ✔, spice-gtk ✔, vte3 ✔
==> Requirements
Required: x11 ✔`

While my co-worker who can still get OS types but has not updated brew in a while gets:
`jeffreywildman/virt-manager/virt-manager: stable 1.4.0
App for managing virtual machines
https://virt-manager.org/
/usr/local/Cellar/virt-manager/1.4.0 (533 files, 12.8M) *
  Built from source on 2016-09-08 at 13:33:26
From: https://github.com/jeffreywildman/homebrew-virt-manager/blob/master/virt-manager.rb
==> Dependencies
Build: intltool ✔, pkg-config ✘
Required: dbus ✘, gnome-icon-theme ✘, gtk+3 ✘, gtk-vnc ✘, hicolor-icon-theme ✔, libosinfo ✘, libvirt ✘, libvirt-glib ✘, libxml2 --with-python ✘, pygobject3 ✘, spice-gtk ✔, vte3 ✘
==> Requirements
Required: x11 ✔`

**Comment by jessiebryan** [comment]
I'm having the same issue - except I don't have any magic like @cmsimike had.
I completely uninstalled virt-manager and the all dependencies - then installed again. 

`jeffreywildman/virt-manager/virt-manager: stable 1.4.0
App for managing virtual machines
https://virt-manager.org/
/usr/local/Cellar/virt-manager/1.4.0 (450 files, 11.8M) *
  Built from source on 2017-02-08 at 09:13:39
From: https://github.com/jeffreywildman/homebrew-virt-manager/blob/master/virt-manager.rb
==> Dependencies
Build: intltool ✔, pkg-config ✔
Required: dbus ✔, gnome-icon-theme ✔, gtk+3 ✔, gtk-vnc ✔, hicolor-icon-theme ✔, libosinfo ✔, libvirt ✔, libvirt-glib ✔, libxml2 --with-python ✔, pygobject3 ✔, spice-gtk ✔, vte3 ✔
==> Requirements
Required: x11 ✔`

**Comment by vchampion** [comment]
I have the same problem, OS X Capitan

**Comment by flexgames** [comment]
@jessiebryan did the reinstall work?

**Comment by flexgames** [comment]
I should also say that I'm having this issue as well...

**Comment by jessiebryan** [comment]
@flexgames - Nope - still stuck.

**Comment by roolebo** [comment]
OS types come from osinfo database.
As of now, the repo doesn't ship osinfo-db-tools and a DB, and the field is empty.

**Comment by roolebo** [comment]
The issue can be workarounded with local formulae. 

First create local formula:
`brew create https://releases.pagure.org/libosinfo/osinfo-db-tools-1.1.0.tar.gz`

And replace generated boilerplate with:
```class OsinfoDbTools < Formula
  desc "Tools for managing the libosinfo database files"
  homepage "https://libosinfo.org"
  url "https://releases.pagure.org/libosinfo/osinfo-db-tools-1.1.0.tar.gz"
  sha256 "a141cd2fc07c30d84801b5dbf6b11f2c2e708b0e81216277d052ac0b57fe546b"
  depends_on "intltool" => :build
  depends_on "pkg-config" => :build
  depends_on "glib"
  depends_on "libarchive"

  def install
    args = %W[
      --prefix=#{prefix}
      --localstatedir=#{var}
      --mandir=#{man}
      --sysconfdir=#{etc}
      --disable-silent-rules
    ]
    system "./configure", *args
    system "make"
    system "make", "install"
  end

  test do
    # `test do` will create, run in and delete a temporary directory.
    #
    # This test will fail and we won't accept that! For Homebrew/homebrew-core
    # this will need to be a test that verifies the functionality of the
    # software. Run the test with `brew test osinfo-db-tools`. Options passed
    # to `brew install` such as `--HEAD` also need to be provided to `brew test`.
    #
    # The installed folder is not in the path, so use the entire path to any
    # executables being tested: `system "#{bin}/program", "do", "something"`.
    system "false"
  end
end
```
Save it, quit from editor and install it:
`brew install osinfo-db-tools`

Then you need to download a database:
`curl -O https://releases.pagure.org/libosinfo/osinfo-db-20180514.tar.xz`

And import it:
`osinfo-db-import osinfo-db-20180514.tar.xz`

Then os types and variants will be available in `virt-install` and `virt-manager`. FWIW, windows 10 is  `win10` os variant and can be installed as:
```
virt-install \
    --name=windows10 \
    --ram=8192 \
    --cpu=host \
    --vcpus=2 \
    --os-type=windows \
    --os-variant=win10 \
    --disk /var/lib/libvirt/images/win10,bus=virtio \
    --disk /path/to/Win10_1803_English_x64.iso,device=cdrom,bus=ide \
    --disk /path/to/virtio-win-0.1.141.iso,device=cdrom,bus=ide \
    --network network=default
```

**Comment by karlfehd** [comment]
Thanks roolebo, that work around fixed it!

**Comment by sandalle** [comment]
Your solution fixed the OS list for me @roolebo , thanks!

**Comment by jeffreywildman** [comment]
@roolebo Thanks for most of the legwork! I've added `osinfo-db-tools` and `osinfo-db` as separate recipes and added `osinfo-db` as a dependency to `virt-manager`.

I now observe a drop down of OS types on my machine. Someone let me know if this fixes the original issue on a machine other than my own and I'll close, thanks!

**Comment by roolebo** [comment]
@jeffreywildman thank you for wrapping the work up. I think the issue can be closed as the latest virt-manager from the tap (1.5.1_2) has non-empty OS fields.
<img width="648" alt="2018-08-20 20 01 25" src="https://user-images.githubusercontent.com/189619/44355057-3086a880-a4b4-11e8-8bfd-51fdc52ee086.png">
