### ISSUE TITLE
brew install virt-manager issue Python-2.3.0

### ISSUE THREAD

**Issue by terroirman** [jeffreywildman/homebrew-virt-manager#66]
Can't install, similar to issue #58 

/usr/local/opt/pkg-config/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
/usr/local/opt/python/bin/python2.7 generator.py libvirt /usr/local/Cellar/libvirt/3.0.0/share/libvirt/api/libvirt-api.xml
Found 418 functions in /usr/local/Cellar/libvirt/3.0.0/share/libvirt/api/libvirt-api.xml
Found 0 functions in libvirt-override-api.xml
Generated 344 wrapper functions
Missing type converters: 
virConnectSecretEventGenericCallback:1 
virStorageVolInfoPtr:1 
ERROR: failed virConnectSecretEventRegisterAny
ERROR: failed virStorageVolGetInfoFlags
error: command '/usr/local/opt/python/bin/python2.7' failed with exit status 1

Changing /usr/local/Homebrew/Library/Taps/jeffreywildman/homebrew-virt-manager/virt-manager.rb resource "libvirt-python" section with the following worked:  

`resource "libvirt-python" do`
      `url "https://libvirt.org/sources/python/libvirt-python-3.0.0.tar.gz"`
       `sha256 "94a7c1c57a643afad43f9068c70774e1146ed051ecfca0280d5127011c5e44c1"`
`end`

**Comment by Nethe** [comment]
Installation worked fine, thanks. But the virt-manager can should be started with --no-fork parameter. 
If not, then it will show the error described on the link below:

[https://pastebin.blesmrt.net/papkeymwz/j0ro0u](url)

**Comment by jeffreywildman** [comment]
Thanks, dependency libvirt-python updated to 3.0.0 in 5de492a8caa48da57584cd27bb0fdbdc93e41842.
