### ISSUE TITLE
fedorahosted.org retired: virt-manager, virt-viewer fail to download

### ISSUE THREAD

**Issue by NicholasPCole** [jeffreywildman/homebrew-virt-manager#67]
It seems fedorahosted.org [was retired yesterday](https://fedoraproject.org/wiki/Infrastructure/Fedorahosted-retirement), so the download URL redirects to the Fedora wiki, causing a SHA256 mismatch:

    (20:41:37)[~@mbp13b:~]$ brew install virt-manager virt-viewer
    ==> Installing virt-manager from jeffreywildman/virt-manager
    ==> Downloading https://fedorahosted.org/released/virt-manager/virt-manager-1.4.0.tar.gz
    ==> Downloading from https://fedoraproject.org/wiki/Infrastructure/Fedorahosted-retirement
    ######################################################################## 100.0%
    Error: SHA256 mismatch
    Expected: bf31a40cc48500cbf87a0e93a5838fc3f6ce4e2fa03f8bce6aa2615625e6caca
    Actual: b73ca62fa3c527fd0e71097ceca802e92b8eae6d711f5547689ea1b3366ea569
    Archive: /Users/nicholas/Library/Caches/Homebrew/virt-manager-1.4.0.tar.gz
    To retry an incomplete download, remove the file above.

Checking the [virt-manager download page](https://virt-manager.org/download/), https://virt-manager.org/download/sources/virt-manager/virt-manager-1.4.0.tar.gz may be an alternative URL for consideration.

The same issue would happen with the virt-viewer download too, but Homebrew doesn't get that far because of the above error.

**Comment by mplessard** [comment]
Hey,

I'm having the same problem. I think we could maybe change the link to this one: 
https://virt-manager.org/download/sources/virt-manager/virt-manager-1.4.0.tar.gz

**Comment by streusselhirni** [comment]
I just successfully installed virt-manager and virt-viewer by using the url you guys mentioned. For the shasum I downloaded the tarballs with curl first, calculated the shasum and put that in the Formula.

Brewing worked, but I cannot confirm that it is running correctly.

**Comment by jeffreywildman** [comment]
Thanks, URLs updated to virt-manager.org.
