### ISSUE TITLE
Unable to install due to missing six python module.

### ISSUE THREAD

**Issue by youvegotmoxie** [jeffreywildman/homebrew-virt-manager#68]
virt-manager is unable to install due the install looking for modules in the wrong location:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 10, in <module>
    from six.moves import filter, map
ImportError: No module named six.moves

mike@snafu-mac:~/ > /usr/local/bin/pip install six
Requirement already satisfied: six in ./Library/Python/2.7/lib/python/site-packages

**Comment by jeffreywildman** [comment]
virt-manager and its Python module dependencies are now all installed and run from a virtualenv environment. I'm hoping this covers your case, or helps provide a more standard way of resolving the issue. Closing the issue for now, but please reopen if it recurs.
