### ISSUE TITLE
No module named gi

### ISSUE THREAD

**Issue by s-anches** [jeffreywildman/homebrew-virt-manager#73]
Hi. macOS Sierra 10.12.5. Today I'm update virt-manager and now virt-manager can't import gi module.
`✘ maxim@MacBook ⮀ ~/Downloads ⮀ virt-manager
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/1.4.1/libexec/share/virt-manager/virt-manager", line 29, in <module>
    import gi
ImportError: No module named gi`

**Comment by compiaffe** [comment]
Same here on same setup.

**Comment by danifunker** [comment]
I've got the same issue here. Looking into it...

**Comment by s-anches** [comment]
Thank you.

**Comment by weijianwen** [comment]
@danifunker you save my day!

```
$ brew reinstall pygobject pygobject3
$ mkdir -p "$HOME/Library/Python/2.7/lib/python/site-packages"
$ echo  'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> "$HOME/Library/Python/2.7/lib/python/site-packages/homebrew.pth"
```

**Comment by jeyakrishnanp** [comment]
@danifunker Thanks it works.

**Comment by dongamp1990** [comment]
@weijianwen thank you.  fix my problem。

**Comment by omkensey** [comment]
I'm getting this error but the above fix does not resolve it.  libvirt-python issues again?

**Comment by zen** [comment]
Same problem here. virt-manager rendered unusable :(

**Comment by zen** [comment]
✘ zen@nandrolone  ~  /usr/local/bin/virt-manager --debug
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/1.5.0/libexec/share/virt-manager/virt-manager", line 31, in <module>
    import gi
ImportError: No module named gi

**Comment by onastvar** [comment]
Same issue as above, macOS 10.13.3 (High Sierra), any ideas how to fix?

**Comment by adamgomes** [comment]
It appears that pygobject no longer contains the gi module. I'm not sure where else to find it right now, though.

**Comment by gabb1** [comment]
yes, broken on high sierra the above tips don't help. 1.4.1 was running fine :(

**Comment by INHack20** [comment]
+1 in macOS 10.13.3 High Sierra

**Comment by weijianwen** [comment]
For me, VirtManager 1.5 is running well on Mac OS X 10.13.3 . I cannot reproduce this issue.

**Comment by INHack20** [comment]
I have executed command "brew reinstall virt-manager" and fix the problem after a "brew upgrade".

Thanks.

**Comment by onastvar** [comment]
i tried 
brew upgrade
brew reinstall virt-manager

I get these errors

==> ./configure --disable-silent-rules --enable-introspection --prefix=/usr/loca
==> make install
Last 15 lines from /Users/macuser/Library/Logs/Homebrew/libvirt-glib/02.make:
  File "/usr/local/Cellar/gobject-introspection/1.56.0_1/lib/gobject-introspection/giscanner/scannermain.py", line 538, in scanner_main
    ss = create_source_scanner(options, args)
  File "/usr/local/Cellar/gobject-introspection/1.56.0_1/lib/gobject-introspection/giscanner/scannermain.py", line 446, in create_source_scanner
    ss.parse_files(filenames)
  File "/usr/local/Cellar/gobject-introspection/1.56.0_1/lib/gobject-introspection/giscanner/sourcescanner.py", line 263, in parse_files
    self._parse(headers)
  File "/usr/local/Cellar/gobject-introspection/1.56.0_1/lib/gobject-introspection/giscanner/sourcescanner.py", line 308, in _parse
    self._cpp_options)
  File "/usr/local/Cellar/gobject-introspection/1.56.0_1/lib/gobject-introspection/giscanner/ccompiler.py", line 210, in preprocess
    extra_postargs=extra_postargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/unixccompiler.py", line 114, in preprocess
    raise CompileError, msg
distutils.errors.CompileError: command 'clang' terminated by signal 10
make[1]: *** [LibvirtGLib-1.0.gir] Error 1
make: *** [install-recursive] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
 libvirt-glib wont build - OSError: [Errno 1] Operation not permitted: g-ir-scanner/ https://github.com/jeffreywildman/homebrew-virt-manager/issues/82
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:426:in `block in dump': undefined method `check_for_bad_install_name_tool' for #<Homebrew::Diagnostic::Checks:0x007fedac289208> (NoMethodError)
Did you mean?  check_for_tap_ruby_files_locations
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `each'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:138:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'

**Comment by Nethe** [comment]
Reinstall was helped, thank you!

> I have executed command "brew reinstall virt-manager" and fix the problem after a "brew upgrade".
> 
> Thanks.



> I have executed command "brew reinstall virt-manager" and fix the problem after a "brew upgrade".
> 
> Thanks.

Confirmed. It helped. Thank you!
