### ISSUE TITLE
missing module gi

### ISSUE THREAD

**Issue by MoritzFago** [jeffreywildman/homebrew-virt-manager#76]
`
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/1.4.1/libexec/share/virt-manager/virt-manager", line 29, in <module>
    import gi
ImportError: No module named gi
`
#23 helps, after the install, you have to add the site-package path to the python path in `/usr/local/bin/virt-manager` so it looks like this:
```
#!/bin/bash
PYTHONPATH="/usr/local/opt/libxml2/lib/python2.7/site-packages:/usr/local/Cellar/virt-manager/1.4.1/libexec/vendor/lib/python2.7/site-packages:/usr/local/lib/python2.7/site-packages" exec "/usr/local/Cellar/virt-manager/1.4.1/libexec/bin/virt-manager" "$@"
```

**Comment by Nethe** [comment]
Hi, just tried this workaround, but it does not work for me:
Still getting below:
`Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/1.4.1/libexec/share/virt-manager/virt-manager", line 30, in <module>
    gi.require_version('LibvirtGLib', '1.0')
AttributeError: 'module' object has no attribute 'require_version'`

In my /usr/local/bin/virt-manager
`#!/bin/bash
PYTHONPATH="/usr/local/opt/libxml2/lib/python2.7/site-packages:/usr/local/Cellar/virt-manager/1.4.1/libexec/vendor/lib/python2.7/site-packages:/usr/local/lib/python2.7/site-packages" exec "/usr/local/Cellar/virt-manager/1.4.1/libexec/bin/virt-manager" "$@"`

Any other ideas please?

**Comment by jeffreywildman** [comment]
virt-manager and its Python module dependencies are now all installed and run from a virtualenv environment. This should include module gi from pygobject3. Closing the issue, but please reopen if it recurs.

**Comment by KTamas** [comment]
I have the same issue.

**Comment by groverz** [comment]
 ~/ cat test
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

window = Gtk.Window(title="Hello World")
window.show()
window.connect("destroy", Gtk.main_quit)
Gtk.main()

 ~/ /usr/bin/env python2 test
Traceback (most recent call last):
  File "1", line 1, in <module>
    import gi
ImportError: No module named gi
 ~/ /usr/bin/env python3 test

work only python3
