### ISSUE TITLE
Install error: [LibvirtGLib-1.0.gir] Error 1

### ISSUE THREAD

**Issue by cboulanger** [jeffreywildman/homebrew-virt-manager#77]
==> Installing virt-manager from jeffreywildman/virt-manager
==> Installing dependencies for jeffreywildman/virt-manager/virt-manager: libvirt-glib, libtool, spice-protocol, libusb, usbredir, spice-gtk, pcre2, vte3
==> Installing jeffreywildman/virt-manager/virt-manager dependency: libvirt-glib
==> Downloading https://libvirt.org/sources/glib/libvirt-glib-1.0.0.tar.gz
Already downloaded: /Users/cboulanger/Library/Caches/Homebrew/libvirt-glib-1.0.0.tar.gz
==> Patching
patching file libvirt-gconfig/Makefile.am
Hunk #1 succeeded at 219 (offset 6 lines).
patching file libvirt-gconfig/Makefile.in
Hunk #1 succeeded at 760 (offset 13 lines).
patching file libvirt-glib/Makefile.am
patching file libvirt-glib/Makefile.in
Hunk #1 succeeded at 441 (offset 5 lines).
patching file libvirt-gobject/Makefile.am
Hunk #1 succeeded at 93 (offset 3 lines).
patching file libvirt-gobject/Makefile.in
Hunk #1 succeeded at 528 (offset 8 lines).
==> ./configure --disable-silent-rules --enable-introspection --prefix=/usr/local/Cellar/libvirt-glib/1.0
==> make install
Last 15 lines from /Users/cboulanger/Library/Logs/Homebrew/libvirt-glib/02.make:
  File "/usr/local/Cellar/gobject-introspection/1.52.1_1/lib/gobject-introspection/giscanner/scannermain.py", line 538, in scanner_main
    ss = create_source_scanner(options, args)
  File "/usr/local/Cellar/gobject-introspection/1.52.1_1/lib/gobject-introspection/giscanner/scannermain.py", line 446, in create_source_scanner
    ss.parse_files(filenames)
  File "/usr/local/Cellar/gobject-introspection/1.52.1_1/lib/gobject-introspection/giscanner/sourcescanner.py", line 262, in parse_files
    self._parse(headers)
  File "/usr/local/Cellar/gobject-introspection/1.52.1_1/lib/gobject-introspection/giscanner/sourcescanner.py", line 305, in _parse
    self._cpp_options)
  File "/usr/local/Cellar/gobject-introspection/1.52.1_1/lib/gobject-introspection/giscanner/ccompiler.py", line 200, in preprocess
    extra_postargs=extra_postargs)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/unixccompiler.py", line 113, in preprocess
    raise CompileError, msg
distutils.errors.CompileError: command 'clang' terminated by signal 10
make[1]: *** [LibvirtGLib-1.0.gir] Error 1
make: *** [install-recursive] Error 1

$ brew config
#HOMEBREW_VERSION: 1.2.6-4-gac2cbd2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: ac2cbd2137006ebfe84d8584ccdcb5d78c1130d9
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3d294562a8de1060285c8f6e4100fff753d1b7cd
Core tap last commit: 38 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit penryn
Homebrew Ruby: 2.0.0-p648
GCC-4.2: build 5666
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_74
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11

**Comment by benleb** [comment]
same problem here :/

**Comment by jeffreywildman** [comment]
Closing issue -- `libvirt-glib` recipe has since been updated to 2.0.0 and merged into [homebrew-core](https://github.com/Homebrew/homebrew-core).
