### ISSUE TITLE
gtk-vnc error

### ISSUE THREAD

**Issue by chayakornc** [jeffreywildman/homebrew-virt-manager#8]
==> Installing virt-manager dependency: gtk-vnc
==> Downloading https://download.gnome.org/sources/gtk-vnc/0.5/gtk-vnc-0.5.3.tar
Already downloaded: /Library/Caches/Homebrew/gtk-vnc-0.5.3.tar.xz
==> ./configure --disable-silent-rules --with-gtk=3.0 --enable-introspection --w
==> make install
clang: error: linker command failed with exit code 1 (use -v to see invocation)
linking of temporary binary failed: Command '['clang', '-o', '/private/tmp/gtk-vnc-OQQLFQ/gtk-vnc-0.5.3/src/tmp-introspectmBhdUT/GVnc-1.0', '/private/tmp/gtk-vnc-OQQLFQ/gtk-vnc-0.5.3/src/tmp-introspectmBhdUT/GVnc-1.0.o', '-L.', '-Wl,-rpath=.', '-Wl,--no-as-needed', './libgvnc-1.0.la', '-L/usr/local/Cellar/glib/2.42.1/lib', '-L/usr/local/opt/gettext/lib', '-lgio-2.0', '-lgmodule-2.0', '-lgobject-2.0', '-lglib-2.0', '-lintl']' returned non-zero exit status 1
make[2]: *** [GVnc-1.0.gir] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1

**Comment by jeffreywildman** [comment]
Sorry, there's not much for me to go on here.  I've updated brew, uninstalled gtk-vnc, and reinstalled it  without any problems on my system.  Try `brew install -v gtk-vnc` for verbose output while installing.

**Comment by jeffreywildman** [comment]
Closed due to inactivity
