### ISSUE TITLE
ERROR: failed virDomainMigrateGetMaxDowntime error: command '/usr/bin/python' failed with exit status 1

### ISSUE THREAD

**Issue by mohammad-javed** [jeffreywildman/homebrew-virt-manager#81]
➜  ~ brew install virt-manager virt-viewer
==> Installing virt-manager from jeffreywildman/virt-manager
==> Downloading https://virt-manager.org/download/sources/virt-manager/virt-manager-1.4.1.tar.gz
Already downloaded: /Users/mjaved/Library/Caches/Homebrew/virt-manager-1.4.1.tar.gz
==> Patching
patching file virt-clone
patching file virt-convert
patching file virt-install
patching file virt-manager
patching file virt-xml
==> Downloading https://libvirt.org/sources/python/libvirt-python-3.4.0.tar.gz
Already downloaded: /Users/mjaved/Library/Caches/Homebrew/virt-manager--libvirt-python-3.4.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/virt-manager/1.4.1/libexec/vendor --single-vers
Last 15 lines from /Users/mjaved/Library/Logs/Homebrew/virt-manager/01.python:
--prefix=/usr/local/Cellar/virt-manager/1.4.1/libexec/vendor
--single-version-externally-managed
--record=installed.txt

running install
running build
/usr/local/opt/pkg-config/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
/usr/bin/python generator.py libvirt /usr/local/Cellar/libvirt/3.7.0/share/libvirt/api/libvirt-api.xml
Found 428 functions in /usr/local/Cellar/libvirt/3.7.0/share/libvirt/api/libvirt-api.xml
Found 0 functions in libvirt-override-api.xml
Generated 348 wrapper functions
Missing type converters:
unsigned long long *:1
ERROR: failed virDomainMigrateGetMaxDowntime
error: command '/usr/bin/python' failed with exit status 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
virt-manager silently quits at launch https://github.com/jeffreywildman/homebrew-virt-manager/issues/78
installation failure for virt-manager https://github.com/jeffreywildman/homebrew-virt-manager/issues/72
Error: jeffreywildman/virt-manager/libvirt-glib 1.0.0 did not build https://github.com/jeffreywildman/homebrew-virt-manager/issues/79
brew install virt-manager issue https://github.com/jeffreywildman/homebrew-virt-manager/issues/58
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62
Add necessary quotes https://github.com/jeffreywildman/homebrew-virt-manager/pull/75
Installation fails: Missing type converters: unsigned long long *:1 ERROR: failed virDomainMigrateGetMaxDowntime https://github.com/jeffreywildman/homebrew-virt-manager/issues/80
missing module gi https://github.com/jeffreywildman/homebrew-virt-manager/issues/76
gi has no attribute 'require_version' https://github.com/jeffreywildman/homebrew-virt-manager/issues/74
Installation fails: Missing type converters https://github.com/jeffreywildman/homebrew-virt-manager/issues/71
Unable to paste from host to client. Copying from client to host works. https://github.com/jeffreywildman/homebrew-virt-manager/issues/35
Unable to connect to libvirt https://github.com/jeffreywildman/homebrew-virt-manager/issues/63
libvirt connection URI ?socket string https://github.com/jeffreywildman/homebrew-virt-manager/issues/61
Can't install libvirt-python on El Capitan https://github.com/jeffreywildman/homebrew-virt-manager/issues/50
Install error: failed virConnectNodeDeviceEventRegisterAny https://github.com/jeffreywildman/homebrew-virt-manager/issues/57
Create new virtual machine OS types missing https://github.com/jeffreywildman/homebrew-virt-manager/issues/64
Error: configure: error: libjpeg not found https://github.com/jeffreywildman/homebrew-virt-manager/issues/49
after brew update  , the same error https://github.com/jeffreywildman/homebrew-virt-manager/issues/55
Crash on re-open VNC console https://github.com/jeffreywildman/homebrew-virt-manager/issues/44
Install error: [LibvirtGLib-1.0.gir] Error 1 https://github.com/jeffreywildman/homebrew-virt-manager/issues/77
Fresh install on 10.11.1: fatal error: 'glib/gi18n-lib.h' file not found https://github.com/jeffreywildman/homebrew-virt-manager/issues/30
Unable to install due to missing six python module. https://github.com/jeffreywildman/homebrew-virt-manager/issues/68
Python quit unexpectedly every time I try and select a drop down box. https://github.com/jeffreywildman/homebrew-virt-manager/issues/45
Docs update about remote connections https://github.com/jeffreywildman/homebrew-virt-manager/issues/42
Error installing spice-gtk: No package 'spice-client-glib-2.0' found https://github.com/jeffreywildman/homebrew-virt-manager/issues/56
➜  ~

**Comment by Toasty27** [comment]
I was having the same issue

Updating the `libvirt-python` resource in `/usr/local/Homebrew/Library/Taps/jeffreywildman/homebrew-virt-manager/virt-manager.rb` to use v3.7.0 instead of 3.4.0 allows for a successful installation:

```
  resource "libvirt-python" do
    url "https://libvirt.org/sources/python/libvirt-python-3.7.0.tar.gz"
    sha256 "1e4a8a8b08ef8f2502088f26ce3aced415d55ef808d8301dfed023f45154c06f"
  end
```

However, now I get the following error when running virt-manager from the command line:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/1.4.1/libexec/share/virt-manager/virt-manager", line 29, in <module>
    import gi
ImportError: No module named gi
```

**Comment by dvukicevic-broadsoft** [comment]
Same Issue for me

**Comment by variablenix** [comment]
This also failed for me.

```
Homebrew 1.3.2
Homebrew/homebrew-core (git revision 66cfb; last commit 2017-09-13)
```

```
==> Downloading https://libvirt.org/sources/python/libvirt-python-3.4.0.tar.gz
Already downloaded: /Users/tony.chavez/Library/Caches/Homebrew/virt-manager--libvirt-python-3.4.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/virt-manager/1.4.1/libexec/vendor --single-version-externall
Last 15 lines from /Users/tony.chavez/Library/Logs/Homebrew/virt-manager/01.python:
--prefix=/usr/local/Cellar/virt-manager/1.4.1/libexec/vendor
--single-version-externally-managed
--record=installed.txt

running install
running build
/usr/local/opt/pkg-config/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
/usr/bin/python generator.py libvirt /usr/local/Cellar/libvirt/3.7.0/share/libvirt/api/libvirt-api.xml
Found 428 functions in /usr/local/Cellar/libvirt/3.7.0/share/libvirt/api/libvirt-api.xml
Found 0 functions in libvirt-override-api.xml
Generated 348 wrapper functions
Missing type converters:
unsigned long long *:1
ERROR: failed virDomainMigrateGetMaxDowntime
error: command '/usr/bin/python' failed with exit status 1
```

**Comment by thestig999** [comment]
Here is a link to a youtube video that helped me solve this problem .   https://www.youtube.com/watch?v=EVlc5G3TzYE&t=292s

I am running virt-manager Mac OSX Sierra.

**Comment by pgajeshwar-coupa** [comment]
Updating libvirt-python version of this file worked for me.
/usr/local/Homebrew/Library/Taps/jeffreywildman/homebrew-virt-manager/virt-manager.rb

```
resource "libvirt-python" do
    url "https://libvirt.org/sources/python/libvirt-python-3.7.0.tar.gz"
    sha256 "1e4a8a8b08ef8f2502088f26ce3aced415d55ef808d8301dfed023f45154c06f"
  end
```

**Comment by e0ne** [comment]
I've got the same error too

**Comment by artooro** [comment]
Has anyone got this working? I tried editing it to use python 3.7 per comment by @pgajeshwar-coupa which allowed it to install. Then I got the error posted by @Toasty27 so I ran `sudo pip install gi` which install gi but now when I try to run virt-manager I get:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/1.4.1/libexec/share/virt-manager/virt-manager", line 30, in <module>
    gi.require_version('LibvirtGLib', '1.0')
AttributeError: 'module' object has no attribute 'require_version'
```

**Comment by artooro** [comment]
Looks like you also need https://github.com/jeffreywildman/homebrew-virt-manager/issues/76 to fix the last gi related issue.

So is anyone doing a pull request or is this project dead?

**Comment by Damenly** [comment]
@artooro  pgajeshwar-coupa's solution works in my MacOS.

**Comment by jeffreywildman** [comment]
Original issue looks like a mismatch in version between libvirt-python and libvirt. Current formula updated to match versions at 4.0.0. Please reinstall/upgrade and create a new issue if it reoccurs.
