### ISSUE TITLE
 libvirt-glib wont build - OSError: [Errno 1] Operation not permitted: g-ir-scanner/

### ISSUE THREAD

**Issue by GioMac** [jeffreywildman/homebrew-virt-manager#82]
here we are:

> bash-4.4$ brew install virt-manager
> ==> Installing virt-manager from jeffreywildman/virt-manager
> ==> Installing dependencies for jeffreywildman/virt-manager/virt-manager: libvirt-glib, spice-gtk, pcre2, vte3
> ==> Installing jeffreywildman/virt-manager/virt-manager dependency: libvirt-glib
> ==> Downloading https://libvirt.org/sources/glib/libvirt-glib-1.0.0.tar.gz
> Already downloaded: /Users/giomac/Library/Caches/Homebrew/libvirt-glib-1.0.0.tar.gz
> ==> Patching
> patching file libvirt-gconfig/Makefile.am
> Hunk #1 succeeded at 219 (offset 6 lines).
> patching file libvirt-gconfig/Makefile.in
> Hunk #1 succeeded at 760 (offset 13 lines).
> patching file libvirt-glib/Makefile.am
> patching file libvirt-glib/Makefile.in
> Hunk #1 succeeded at 441 (offset 5 lines).
> patching file libvirt-gobject/Makefile.am
> Hunk #1 succeeded at 93 (offset 3 lines).
> patching file libvirt-gobject/Makefile.in
> Hunk #1 succeeded at 528 (offset 8 lines).
> ==> ./configure --disable-silent-rules --enable-introspection --prefix=/usr/local/Cellar/libvirt-glib/1.0.0
> ==> make install
> Last 15 lines from /Users/giomac/Library/Logs/Homebrew/libvirt-glib/02.make:
>   File "/usr/local/Cellar/gobject-introspection/1.52.1_1/lib/gobject-introspection/giscanner/scannermain.py", line 386, in create_transformer
>     symbol_filter_cmd=options.symbol_filter_cmd)
>   File "/usr/local/Cellar/gobject-introspection/1.52.1_1/lib/gobject-introspection/giscanner/transformer.py", line 54, in __init__
>     self._cachestore = CacheStore()
>   File "/usr/local/Cellar/gobject-introspection/1.52.1_1/lib/gobject-introspection/giscanner/cachestore.py", line 61, in __init__
>     self._check_cache_version()
>   File "/usr/local/Cellar/gobject-introspection/1.52.1_1/lib/gobject-introspection/giscanner/cachestore.py", line 89, in _check_cache_version
>     self._clean()
>   File "/usr/local/Cellar/gobject-introspection/1.52.1_1/lib/gobject-introspection/giscanner/cachestore.py", line 141, in _clean
>     self._remove_filename(os.path.join(self._directory, filename))
>   File "/usr/local/Cellar/gobject-introspection/1.52.1_1/lib/gobject-introspection/giscanner/cachestore.py", line 123, in _remove_filename
>     os.unlink(filename)
> OSError: [Errno 1] Operation not permitted: '/Users/user/.cache/g-ir-scanner/49ec1699c494570325df0aa02ff514a44d713dfc'
> make[1]: *** [LibvirtGLib-1.0.gir] Error 1
> make: *** [install-recursive] Error 1

**Comment by lunixbochs** [comment]
You might need to `chown -R username:staff ~/.cache`.

**Comment by GioMac** [comment]
@lunixbochs nope, that doesn't help, even with chmod 777 in the root of cache, directory is created later

**Comment by GioMac** [comment]
#84  didn't help too

**Comment by lunixbochs** [comment]
what if you delete .cache?

**Comment by lunixbochs** [comment]
#83 builds on fresh osx just fine, so if there's a problem building #83 it's your environment

**Comment by GioMac** [comment]
@lunixbochs nothing helps
my environment might be a complicated, that's true, usually when you are linux user and use libvirt - your environment on Mac OS X laptop won't be "clean", ever :(

**Comment by GioMac** [comment]
@lunixbochs btw, it's libvirt-glib issue, so, other patches do nothing

**Comment by lunixbochs** [comment]
Enable dtrace (using csrutil/SIP) and run dtruss -ff on brew.

**Comment by GioMac** [comment]
@lunixbochs 
[brew-dtrace-libvirt-glib.txt](https://github.com/jeffreywildman/homebrew-virt-manager/files/1404732/brew-dtrace-libvirt-glib.txt)

**Comment by lunixbochs** [comment]
.cache isn't in that trace at all. Did it still error out?

**Comment by GioMac** [comment]
@lunixbochs hm, sorry, looks like i've got trouble running dtruss with regular user:
"dtruss -ff brew install libvirt-glibc
dtrace: failed to initialize dtrace: DTrace requires additional privileges"
can't run with root or "-u" because of this:
"Running Homebrew as root is extremely dangerous and no longer supported."
any clue?

**Comment by lunixbochs** [comment]
put brew cmd in a shell script that starts with a single line of `read` then attach dtruss -ff -p pid with the pid before pressing enter

**Comment by GioMac** [comment]
@lunixbochs not understood, can you please provide the script?

**Comment by benleb** [comment]
same problem here :/

**Comment by jeffreywildman** [comment]
Closing issue -- `libvirt-glib` recipe has since been updated to 2.0.0 and merged into [homebrew-core](https://github.com/Homebrew/homebrew-core).
