### ISSUE TITLE
ERROR: failed virDomainMigrateGetMaxDowntime

### ISSUE THREAD

**Issue by lowang-bh** [jeffreywildman/homebrew-virt-manager#89]
There is a error whilc install this manager show as following:

```
==> Installing virt-manager from jeffreywildman/virt-manager
==> Downloading https://virt-manager.org/download/sources/virt-manager/virt-manager-1.4.1.tar.gz
Already downloaded: /Users/wang/Library/Caches/Homebrew/virt-manager-1.4.1.tar.gz
==> Patching
patching file virt-clone
patching file virt-convert
patching file virt-install
patching file virt-manager
patching file virt-xml
==> Downloading https://libvirt.org/sources/python/libvirt-python-3.4.0.tar.gz
Already downloaded: /Users/wang/Library/Caches/Homebrew/virt-manager--libvirt-python-3.4.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/virt-manager/1.4.1/libexec/vend
Last 15 lines from /Users/wang/Library/Logs/Homebrew/virt-manager/01.python:
--prefix=/usr/local/Cellar/virt-manager/1.4.1/libexec/vendor
--single-version-externally-managed
--record=installed.txt

running install
running build
/usr/local/opt/pkg-config/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
/usr/bin/python generator.py libvirt /usr/local/Cellar/libvirt/4.0.0/share/libvirt/api/libvirt-api.xml
Found 429 functions in /usr/local/Cellar/libvirt/4.0.0/share/libvirt/api/libvirt-api.xml
Found 0 functions in libvirt-override-api.xml
Generated 349 wrapper functions
Missing type converters: 
unsigned long long *:1 
ERROR: failed virDomainMigrateGetMaxDowntime
error: command '/usr/bin/python' failed with exit status 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
brew install virt-manager issue https://github.com/jeffreywildman/homebrew-virt-manager/issues/58
installation failure for virt-manager https://github.com/jeffreywildman/homebrew-virt-manager/issues/72
virt-manager silently quits at launch https://github.com/jeffreywildman/homebrew-virt-manager/issues/78
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62
Error: jeffreywildman/virt-manager/libvirt-glib 1.0.0 did not build https://github.com/jeffreywildman/homebrew-virt-manager/issues/79

```

**Comment by dguenard** [comment]
again !

==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/virt-manager/1.4.1/libexec/vendor --single-version-externally-managed --rec
Last 15 lines from /Users/guenar01/Library/Logs/Homebrew/virt-manager/01.python:
--prefix=/usr/local/Cellar/virt-manager/1.4.1/libexec/vendor
--single-version-externally-managed
--record=installed.txt

running install
running build
/usr/local/opt/pkg-config/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
/usr/bin/python generator.py libvirt /usr/local/Cellar/libvirt/4.0.0/share/libvirt/api/libvirt-api.xml
Found 429 functions in /usr/local/Cellar/libvirt/4.0.0/share/libvirt/api/libvirt-api.xml
Found 0 functions in libvirt-override-api.xml
Generated 349 wrapper functions
Missing type converters: 
unsigned long long *:1 
ERROR: failed virDomainMigrateGetMaxDowntime
error: command '/usr/bin/python' failed with exit status 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
brew install virt-manager issue https://github.com/jeffreywildman/homebrew-virt-manager/issues/58
installation failure for virt-manager https://github.com/jeffreywildman/homebrew-virt-manager/issues/72
virt-manager silently quits at launch https://github.com/jeffreywildman/homebrew-virt-manager/issues/78
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62
Error: jeffreywildman/virt-manager/libvirt-glib 1.0.0 did not build https://github.com/jeffreywildman/homebrew-virt-manager/issues/79

**Comment by jeffreywildman** [comment]
Looks like a mismatch in libvirt-python and libvirt versions. Recent updates to formula match at 4.0.0. Closing for now, please try to update/reinstall.
