### ISSUE TITLE
Missing type converters: unsigned long long *:1

### ISSUE THREAD

**Issue by lotusdocker** [jeffreywildman/homebrew-virt-manager#90]
my osx system version is EI Capitan
Here are some error messages

==> Downloading https://libvirt.org/sources/python/libvirt-python-3.4.0.tar.gz
Already downloaded: /Users/chaos/Library/Caches/Homebrew/virt-manager--libvirt-python-3.4.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/virt-manager/1.4.1/libexec/vendor --
Last 15 lines from /Users/chaos/Library/Logs/Homebrew/virt-manager/01.python:
--prefix=/usr/local/Cellar/virt-manager/1.4.1/libexec/vendor
--single-version-externally-managed
--record=installed.txt

running install
running build
/usr/local/opt/pkg-config/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
/usr/bin/python generator.py libvirt /usr/local/Cellar/libvirt/4.0.0/share/libvirt/api/libvirt-api.xml
Found 429 functions in /usr/local/Cellar/libvirt/4.0.0/share/libvirt/api/libvirt-api.xml
Found 0 functions in libvirt-override-api.xml
Generated 349 wrapper functions
Missing type converters:
unsigned long long *:1
ERROR: failed virDomainMigrateGetMaxDowntime
error: command '/usr/bin/python' failed with exit status 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
brew install virt-manager issue https://github.com/jeffreywildman/homebrew-virt-manager/issues/58
installation failure for virt-manager https://github.com/jeffreywildman/homebrew-virt-manager/issues/72
virt-manager silently quits at launch https://github.com/jeffreywildman/homebrew-virt-manager/issues/78
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62
Error: jeffreywildman/virt-manager/libvirt-glib 1.0.0 did not build https://github.com/jeffreywildman/homebrew-virt-manager/issues/79

I can not find a solution :(

**Comment by jeffreywildman** [comment]
Just updated the formula to libvirt-python-4.0.0 to match libvirt available on homebrew-core. Try reinstalling.
