### ISSUE TITLE
[Install Error]-Error: Failure while executing: patch -g 0 -f -p1

### ISSUE THREAD

**Issue by tasi788** [jeffreywildman/homebrew-virt-manager#93]
```
$ brew install virt-manager
==> Installing virt-manager from jeffreywildman/virt-manager
==> Installing dependencies for jeffreywildman/virt-manager/virt-manager: libvirt-glib, python, py3cairo, pygobject3, bdw-gc, guile, autogen, automake, lz4, spice-protocol, usbredir, bison, gstreamer, orc, gst-plugins-base, gst-libav, gst-plugins-good, gst-plugins-bad, gst-plugins-ugly, spice-gtk, pcre2, vte3
==> Installing jeffreywildman/virt-manager/virt-manager dependency
==> Downloading https://libvirt.org/sources/glib/libvirt-glib-1.0.
Already downloaded: /Users/TSAI/Library/Caches/Homebrew/libvirt-glib-1.0.0.tar.gz
==> Patching
patching file libvirt-gconfig/Makefile.am
Hunk #1 succeeded at 219 (offset 6 lines).
can't find file to patch at input line 19
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/libvirt-gconfig/Makefile.in b/libvirt-gconfig/Makefile.in
|index 42e4352..67d7fae 100644
|--- a/libvirt-gconfig/Makefile.in
|+++ b/libvirt-gconfig/Makefile.in
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
patching file libvirt-glib/Makefile.am
can't find file to patch at input line 47
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/libvirt-glib/Makefile.in b/libvirt-glib/Makefile.in
|index 3523684..47c4417 100644
|--- a/libvirt-glib/Makefile.in
|+++ b/libvirt-glib/Makefile.in
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
patching file libvirt-gobject/Makefile.am
Hunk #1 succeeded at 93 (offset 3 lines).
can't find file to patch at input line 75
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/libvirt-gobject/Makefile.in b/libvirt-gobject/Makefile.in
|index 26e0df6..0ffa15c 100644
|--- a/libvirt-gobject/Makefile.in
|+++ b/libvirt-gobject/Makefile.in
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
Error: Failure while executing: patch -g 0 -f -p1
```
--
OS X : 10.12.6

**Comment by jeffreywildman** [comment]
Please try `brew install libvirt-glib` to isolate the issue.

**Comment by tasi788** [comment]
@jeffreywildman thx for replying
it works, but now have another problem
`==> Pouring gst-plugins-ugly-1.14.0_1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gst-plugins-ugly/1.14.0_1: 91 files, 1.5MB
==> Installing jeffreywildman/virt-manager/virt-manager dependency: spice-gtk
==> Downloading https://www.spice-space.org/download/gtk/spice-gtk-0.34.tar.bz2
######################################################################## 100.0%
==> Patching
patching file configure.ac
patching file src/Makefile.am
patching file spice-common/m4/spice-deps.m4
==> autoreconf -v --force --install
==> ./configure --disable-silent-rules --with-gtk=3.0 --enable-introspection --enable-vala
==> make install
Last 15 lines from /Users/TSAI/Library/Logs/Homebrew/spice-gtk/03.make:
libtool: link: sed 's|^|_|' < ./spice-gtk-sym-file > .libs/libspice-client-gtk-3.0-symbols.expsym
libtool: link: clang -dynamiclib  -o .libs/libspice-client-gtk-3.0.5.dylib  .libs/spice-util.o .libs/spice-gtk-session.o .libs/spice-widget.o .libs/vncdisplaykeymap.o .libs/spice-grabsequence.o .libs/desktop-integration.o .libs/usb-device-widget.o .libs/spice-widget-cairo.o .libs/spice-widget-enums.o .libs/spice-marshal.o   ./.libs/libspice-client-glib-2.0.dylib -L/usr/local/Cellar/pixman/0.34.0_1/lib -L/usr/local/Cellar/glib/2.56.0/lib -L/usr/local/opt/gettext/lib -L/usr/local/Cellar/openssl/1.0.2o_1/lib -L/usr/local/Cellar/lz4/1.8.1.2/lib -L/usr/local/Cellar/gstreamer/1.14.0_1/lib -L/usr/local/Cellar/gst-plugins-base/1.14.0_1/lib -L/usr/local/Cellar/libusb/1.0.21/lib -L/usr/local/Cellar/usbredir/0.7.1/lib -ljpeg -lz -llz4 -lpixman-1 -lssl -lcrypto -lgstaudio-1.0 -lgstapp-1.0 -lgstvideo-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lusb-1.0 -lusbredirhost -lusbredirparser -lgthread-2.0 -L/usr/local/Cellar/cairo/1.14.12/lib -L/usr/local/Cellar/gdk-pixbuf/2.36.11_1/lib -L/usr/local/Cellar/atk/2.28.1_1/lib -L/usr/local/Cellar/libepoxy/1.5.0/lib -L/usr/local/Cellar/pango/1.42.0_1/lib -L/usr/local/Cellar/gtk+3/3.22.29_1/lib -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl -lepoxy -lcairo  -g -O2 -Wl,-framework -Wl,CoreFoundation   -install_name  /usr/local/Cellar/spice-gtk/0.34/lib/libspice-client-gtk-3.0.5.dylib -compatibility_version 6 -current_version 6.0 -Wl,-single_module -Wl,-exported_symbols_list,.libs/libspice-client-gtk-3.0-symbols.expsym
libtool: link: (cd ".libs" && rm -f "libspice-client-gtk-3.0.dylib" && ln -s "libspice-client-gtk-3.0.5.dylib" "libspice-client-gtk-3.0.dylib")
libtool: link: ( cd ".libs" && rm -f "libspice-client-gtk-3.0.la" && ln -s "../libspice-client-gtk-3.0.la" "libspice-client-gtk-3.0.la" )
g-ir-scanner: link: /bin/sh ../libtool --mode=link --tag=CC clang -o /private/tmp/spice-gtk-20180329-19345-1d0sigg/spice-gtk-0.34/src/tmp-introspectEZvv2z/SpiceClientGLib-2.0 -export-dynamic -Wno-cast-align -Wno-error /private/tmp/spice-gtk-20180329-19345-1d0sigg/spice-gtk-0.34/src/tmp-introspectEZvv2z/SpiceClientGLib-2.0.o -L. libspice-client-glib-2.0.la -L/usr/local/Cellar/glib/2.56.0/lib -L/usr/local/opt/gettext/lib -lgio-2.0 -lgobject-2.0 -lgmodule-2.0 -lglib-2.0 -lintl -Wl,-framework -Wl,CoreFoundation
libtool: link: clang -o /private/tmp/spice-gtk-20180329-19345-1d0sigg/spice-gtk-0.34/src/tmp-introspectEZvv2z/.libs/SpiceClientGLib-2.0 -Wno-cast-align -Wno-error /private/tmp/spice-gtk-20180329-19345-1d0sigg/spice-gtk-0.34/src/tmp-introspectEZvv2z/SpiceClientGLib-2.0.o -Wl,-framework -Wl,CoreFoundation  -L. ./.libs/libspice-client-glib-2.0.dylib -L/usr/local/Cellar/pixman/0.34.0_1/lib -L/usr/local/Cellar/glib/2.56.0/lib -L/usr/local/opt/gettext/lib -L/usr/local/Cellar/openssl/1.0.2o_1/lib -L/usr/local/Cellar/lz4/1.8.1.2/lib -L/usr/local/Cellar/gstreamer/1.14.0_1/lib -L/usr/local/Cellar/gst-plugins-base/1.14.0_1/lib -L/usr/local/Cellar/libusb/1.0.21/lib -L/usr/local/Cellar/usbredir/0.7.1/lib -ljpeg -lz -llz4 -lpixman-1 -lssl -lcrypto -lgstaudio-1.0 -lgstapp-1.0 -lgstvideo-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lusb-1.0 -lusbredirhost -lusbredirparser -lgthread-2.0 -lgio-2.0 -lgobject-2.0 -lgmodule-2.0 -lglib-2.0 -lintl
/usr/local/Cellar/gobject-introspection/1.56.0/bin/g-ir-compiler --includedir=. --includedir=. SpiceClientGLib-2.0.gir -o SpiceClientGLib-2.0.typelib
CPPFLAGS="" CFLAGS="-Wno-cast-align -Wno-error" LDFLAGS="" CC="clang" PKG_CONFIG="/usr/local/opt/pkg-config/bin/pkg-config" GI_HOST_OS="" DLLTOOL="false"  /usr/local/Cellar/gobject-introspection/1.56.0/bin/g-ir-scanner  --warn-all --accept-unprefixed --add-include-path=. --symbol-prefix=spice --identifier-prefix=Spice --namespace=SpiceClientGtk --nsversion=3.0 --libtool="/bin/sh ../libtool"  --include=GObject-2.0 --include=Gtk-3.0 --include=SpiceClientGLib-2.0 --pkg-export=spice-client-gtk-3.0   --library=libspice-client-gtk-3.0.la --library=libspice-client-glib-2.0.la --c-include="spice-widget.h" --cflags-begin -DSPICE_COMPILATION -DG_LOG_DOMAIN=\"GSpice\" -DSPICE_GTK_LOCALEDIR=\"/usr/local/Cellar/spice-gtk/0.34/share/locale\" -DPNP_IDS=\""/pnp.ids"\" -DUSB_IDS=\"""\" -I.. -I../spice-common/ -I../spice-common/ -I/usr/local/Cellar/spice-protocol/0.12.13/include/spice-1 -I/usr/local/Cellar/pixman/0.34.0_1/include/pixman-1  -D_REENTRANT -I/usr/local/Cellar/libpng/1.6.34/include/libpng16 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.6/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/pixman/0.34.0_1/include/pixman-1 -I/usr/local/Cellar/pcre/8.42/include -I/usr/local/Cellar/glib/2.56.0/include/gio-unix-2.0/ -I/usr/local/Cellar/glib/2.56.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.56.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/cairo/1.14.12/include/cairo -I/usr/local/Cellar/gdk-pixbuf/2.36.11_1/include/gdk-pixbuf-2.0 -I/usr/local/Cellar/atk/2.28.1_1/include/atk-1.0 -I/usr/local/Cellar/libepoxy/1.5.0/include -I/usr/local/Cellar/graphite2/1.3.10/include -I/usr/local/Cellar/harfbuzz/1.7.6/include/harfbuzz -I/usr/local/Cellar/pango/1.42.0_1/include/pango-1.0 -I/usr/local/Cellar/gtk+3/3.22.29_1/include/gtk-3.0 -DGDK_VERSION_MIN_REQUIRED=GDK_VERSION_3_12                                -DGDK_VERSION_MAX_ALLOWED=GDK_VERSION_3_12 -I/usr/local/Cellar/libpng/1.6.34/include/libpng16 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.6/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/pixman/0.34.0_1/include/pixman-1 -I/usr/local/Cellar/pcre/8.42/include -I/usr/local/Cellar/glib/2.56.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.56.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/cairo/1.14.12/include/cairo -I/usr/local/Cellar/pcre/8.42/include -I/usr/local/Cellar/glib/2.56.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.56.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_36   -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_36 -D_REENTRANT -I/usr/local/Cellar/pcre/8.42/include -I/usr/local/Cellar/glib/2.56.0/include/gio-unix-2.0/ -I/usr/local/Cellar/glib/2.56.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.56.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.42/include -I/usr/local/Cellar/glib/2.56.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.56.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/openssl/1.0.2o_1/include  -D_REENTRANT -I/usr/local/Cellar/pcre/8.42/include -I/usr/local/Cellar/glib/2.56.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.56.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/gstreamer/1.14.0_1/include/gstreamer-1.0 -I/usr/local/Cellar/orc/0.4.28/include/orc-0.4 -I/usr/local/Cellar/gst-plugins-base/1.14.0_1/include/gstreamer-1.0 -D_REENTRANT -I/usr/local/Cellar/pcre/8.42/include -I/usr/local/Cellar/glib/2.56.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.56.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/gstreamer/1.14.0_1/include/gstreamer-1.0 -I/usr/local/Cellar/orc/0.4.28/include/orc-0.4 -I/usr/local/Cellar/gst-plugins-base/1.14.0_1/include/gstreamer-1.0  -I/usr/local/Cellar/libusb/1.0.21/include/libusb-1.0 -I/usr/local/Cellar/usbredir/0.7.1/include     -I/usr/local/Cellar/lz4/1.8.1.2/include  --cflags-end  spice-client-gtk.h spice-gtk-session.h spice-widget.h spice-grabsequence.h usb-device-widget.h spice-widget-enums.h spice-gtk-session.c spice-widget.c spice-grabsequence.c usb-device-widget.c libspice-client-gtk-3.0.la SpiceClientGLib-2.0.gir --output SpiceClientGtk-3.0.gir
Couldn't find include 'Gtk-3.0.gir' (search path: '['.', u'gir-1.0', u'/usr/local/Cellar/gobject-introspection/1.56.0/share/gir-1.0', u'/usr/local/share/gir-1.0', u'/usr/local/Cellar/gobject-introspection/1.56.0/share/gir-1.0']')
make[4]: *** [SpiceClientGtk-3.0.gir] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [install-recursive] Error 1
make[2]: *** [install] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/jeffreywildman/homebrew-virt-manager/issues`
