### ISSUE TITLE
Tons of "TypeError: Couldn't find foreign struct converter for 'cairo.Context'"

### ISSUE THREAD

**Issue by hit0wnzzz** [jeffreywildman/homebrew-virt-manager#96]
10.11.6.

virt-manager connects to host but doesn't show graphs and during execution I get A LOT of:

"TypeError: Couldn't find foreign struct converter for 'cairo.Context'"
"TypeError: Couldn't find foreign struct converter for 'cairo.Context'"
"TypeError: Couldn't find foreign struct converter for 'cairo.Context'"

**Comment by piphoser** [comment]
Same exact problem here.  It is associated with the guest CPU usage graph.  Turn that graph off and the error will go away - unfortunately, you won't see CPU utilization after that.

**Comment by hit0wnzzz** [comment]
but i really like the graphs :(

**Comment by blu3knight** [comment]
So is there a fix for this? I would rather have something installed instead of just saying turn off this and that. What package installation would solve this?

**Comment by jeffreywildman** [comment]
I've been able to reproduce these error messages on my machine and resolve it by adding `py2cairo` as a dependency. I've pushed to `master`, let me know if this works for you and I'll close the issue.

**Comment by benleb** [comment]
Its not working for me. As I already had py2cairo installed before, i tried reinstalling everything but makes no difference. Sorry :/
