### ISSUE TITLE
curl error on installation

### ISSUE THREAD

**Issue by dougbevan** [jeffreywildman/homebrew-virt-manager#97]
Hello.

Attempting to install, the following results:

➜ brew install virt-manager virt-viewer
==> Installing virt-manager from jeffreywildman/virt-manager
==> Downloading https://virt-manager.org/download/sources/virt-manager/virt-manager-1.5.1.tar.gz
Already downloaded: /Users/doug/Library/Caches/Homebrew/virt-manager-1.5.1.tar.gz
==> Patching
patching file virt-manager
==> Downloading https://files.pythonhosted.org/packages/33/bc/fa0b5347139cd9564f0d44ebd2b147ac97c36b2403943dbee8a25fd74012/virtualenv-16.0.0.tar.gz

curl: (35) getpeername() failed with errno 22: Invalid argument
Error: Failed to download resource "virt-manager--homebrew-virtualenv"
Download failed: https://files.pythonhosted.org/packages/33/bc/fa0b5347139cd9564f0d44ebd2b147ac97c36b2403943dbee8a25fd74012/virtualenv-16.0.0.tar.gz

**Comment by jeffreywildman** [comment]
This looks like a network issue, the supplied virtualenv URL is accessible to me.
